using System.Collections.Generic;

namespace DeskArcade;

public static partial class Strings
{
    static readonly Dictionary<string, string> RussianTable = new()
    {
        // ---- menus, notices, overlay
        ["Automatic"] = "Автоматически",
        ["Game"] = "Игра",
        ["Games"] = "Игры",
        ["General"] = "Общие",
        ["Next game"] = "Следующая игра",
        ["Bring to cursor"] = "Переместить к курсору",
        ["Stats & achievements"] = "Статистика и достижения",
        ["Stats & achievements…"] = "Статистика и достижения…",
        ["Show overlay"] = "Показать игру",
        ["Bounce on window tops"] = "Отскок от верха окон",
        ["Sound"] = "Звук",
        ["Volume"] = "Громкость",
        ["Language"] = "Язык",
        ["Alerts when Claude finishes"] = "Оповещать, когда Claude закончит",
        ["Show the overlay when Claude starts working"] = "Показывать игру, когда Claude начинает работу",
        ["Hide the overlay when Claude finishes or needs you"] = "Скрывать игру, когда Claude закончил или ждёт вас",
        ["Copy Claude Code hook config"] = "Скопировать настройки хуков Claude Code",
        ["Start when I sign in"] = "Запускать при входе в систему",
        ["Move to next monitor"] = "На следующий монитор",
        ["Check for updates"] = "Проверить обновления",
        ["Check for updates automatically"] = "Проверять обновления автоматически",
        ["Download version {0}…"] = "Скачать версию {0}…",
        ["Reset positions"] = "Сбросить расположение",
        ["Reset high scores"] = "Сбросить рекорды",
        ["Reset stats and achievements"] = "Сбросить статистику и достижения",
        ["Exit"] = "Выход",
        ["Welcome to Desk Arcade"] = "Добро пожаловать в Desk Arcade",
        ["click the scoreboard to pick a game · {0} show/hide · {1} next game"] =
            "нажмите на табло, чтобы выбрать игру · {0} показать/скрыть · {1} следующая игра",
        ["Achievement unlocked"] = "Достижение получено",
        ["Stats reset"] = "Статистика сброшена",
        ["achievements start over"] = "достижения начнутся заново",
        ["Hook config copied"] = "Настройки хуков скопированы",
        ["merge it into ~/.claude/settings.json"] = "добавьте их в ~/.claude/settings.json",
        ["Desk Arcade {0} is available"] = "Доступна Desk Arcade {0}",
        ["opening the download page"] = "открываем страницу загрузки",
        ["download it from the tray menu"] = "скачайте через меню в трее",
        ["You're up to date"] = "У вас последняя версия",
        ["version {0}"] = "версия {0}",
        ["Time played {0} · achievements {1}/{2}"] = "Время в игре {0} · достижения {1}/{2}",
        ["{0}h {1}m"] = "{0} ч {1} мин",
        ["{0}m"] = "{0} мин",

        // ---- commands run with --while
        ["{0} passed · {1}"] = "{0} прошло · {1}",
        ["{0} passed"] = "{0} прошло",
        ["{0} failed · exit {1}"] = "{0} упало · код {1}",
        ["{0} · took {1}"] = "{0} · заняло {1}",
        ["{0} · exit code {1}"] = "{0} · код выхода {1}",
        ["{0} · you played {1}"] = "{0} · вы играли {1}",
        ["Passed"] = "Готово",
        ["Failed"] = "Ошибка",
        ["It's compiling"] = "Оно компилируется",
        ["Be playing when a --while command finishes 10 times"] = "Играйте в момент, когда команда --while завершится, 10 раз",

        // ---- Claude Code
        ["Claude working"] = "Claude работает",
        ["Claude working · {0}"] = "Claude работает · {0}",
        ["Claude done"] = "Claude закончил",
        ["Claude done after {0}"] = "Claude закончил за {0}",
        ["Claude is done"] = "Claude закончил",
        ["Claude needs you"] = "Claude ждёт вас",
        ["your turn!"] = "ваш ход!",
        ["check the terminal"] = "загляните в терминал",
        ["{0} · waited {1}"] = "{0} · ожидание {1}",

        // ---- game titles and switch hints
        ["Hoops"] = "Баскетбол",
        ["Archery"] = "Стрельба из лука",
        ["Keepy-Uppy"] = "Чеканка",
        ["Mini Golf"] = "Мини-гольф",
        ["Bug Squash"] = "Давилка багов",
        ["Can Knockdown"] = "Сбей банки",
        ["Brick Breaker"] = "Арканоид",
        ["Bubble Pop"] = "Лопни пузыри",
        ["Air Hockey"] = "Аэрохоккей",
        ["Clay Shooting"] = "Стендовая стрельба",
        ["Whack-a-Bug"] = "Прихлопни бага",
        ["Plinko"] = "Плинко",
        ["Tower Stack"] = "Башня",
        ["drag the ball and flick it into the hoop"] = "тяните мяч и бросайте в кольцо",
        ["drag back from the bow, release to shoot"] = "оттяните тетиву и отпустите для выстрела",
        ["click the ball to kick it — don't let it drop"] = "нажимайте на мяч, чтобы подбить — не роняйте",
        ["drag back from the ball to putt it into the cup"] = "оттяните от мяча и ударьте в лунку",
        ["squash the bugs — spare the ladybugs"] = "давите багов — божьих коровок не трогайте",
        ["throw the ball from behind the line"] = "бросайте мяч из-за линии",
        ["click the paddle to launch — the mouse steers it"] = "нажмите на ракетку, чтобы запустить — ею управляет мышь",
        ["click a bubble to split it — clear them all in time"] = "нажмите на пузырь, чтобы разделить — успейте лопнуть все",
        ["drag your mallet and score in the right-hand goal"] = "двигайте биту и забивайте в правые ворота",
        ["click the trap machine, then shoot the clays at the top of their arc"] = "нажмите на метательную машину и стреляйте по тарелкам в верхней точке",
        ["whack the bugs as they peek out — spare the ladybugs"] = "бейте багов, когда они выглядывают — божьих коровок не трогайте",
        ["click the strip to drop a disc — the gold slot is the jackpot"] = "нажмите на полосу, чтобы бросить диск — золотая ячейка это джекпот",
        ["click the sliding block to drop it — stack as high as you can"] = "нажмите на движущийся блок, чтобы сбросить — стройте как можно выше",

        // ---- shared game text
        ["Best {0}"] = "Рекорд {0}",
        ["NEW BEST!"] = "НОВЫЙ РЕКОРД!",
        ["NEW BEST ROUND!"] = "РЕКОРД РАУНДА!",
        ["GAME OVER"] = "ИГРА ОКОНЧЕНА",
        ["ROUND OVER"] = "РАУНД ОКОНЧЕН",
        ["TIME!"] = "ВРЕМЯ!",
        ["{0} points"] = "очков: {0}",
        ["that was a feature!"] = "это была фича!",

        // ---- Hoops
        ["Drag the ball, flick it into the hoop"] = "Тяните мяч и бросайте в кольцо",
        ["Streak {0} · keep going!"] = "Серия {0} · так держать!",
        ["Streak {0} · ON FIRE ×2"] = "Серия {0} · В ОГНЕ ×2",
        ["Best streak {0}"] = "Лучшая серия {0}",
        ["streak over"] = "серия прервана",
        ["DUNK!"] = "ДАНК!",
        ["SWISH!"] = "ЧИСТО!",
        ["SWISH THREE!"] = "ЧИСТЫЙ ТРЁХОЧКОВЫЙ!",
        ["THREE POINTER!"] = "ТРЁХОЧКОВЫЙ!",
        ["NICE SHOT!"] = "ОТЛИЧНЫЙ БРОСОК!",
        ["ON FIRE!"] = "В ОГНЕ!",
        ["points ×2"] = "очки ×2",
        ["MOVING HOOP!"] = "КОЛЬЦО ДВИЖЕТСЯ!",
        ["NEW BEST STREAK"] = "НОВАЯ ЛУЧШАЯ СЕРИЯ",

        // ---- Archery
        ["calm"] = "штиль",
        ["Round {0} · {1} arrows · wind {2}"] = "Раунд {0} · стрел {1} · ветер {2}",
        ["Round over · pull the bow to play again"] = "Раунд окончен · натяните лук, чтобы сыграть снова",
        ["Best round {0}"] = "Лучший раунд {0}",
        ["pull back to start a round"] = "натяните, чтобы начать раунд",
        ["{0} arrows · wind {1}"] = "стрел {0} · ветер {1}",
        ["{0} points · best {1}"] = "очков: {0} · рекорд {1}",
        ["BULLSEYE!"] = "В ЯБЛОЧКО!",
        ["GOLDEN!"] = "ЗОЛОТОЙ!",
        ["POP!"] = "ХЛОП!",

        // ---- Keepy-Uppy
        ["Click the ball to kick it up"] = "Нажмите на мяч, чтобы подбить его",
        ["Juggles {0} · grab the star!"] = "Набивания {0} · хватайте звезду!",
        ["Juggles {0} · don't let it drop"] = "Набивания {0} · не роняйте",
        ["Dropped!"] = "Упал!",

        // ---- Mini Golf
        ["Hole {0}/{1} · par {2} · stroke {3}"] = "Лунка {0}/{1} · пар {2} · удар {3}",
        ["Round done · {0} vs par · putt to play again"] = "Раунд окончен · {0} к пару · ударьте, чтобы сыграть снова",
        ["Best —"] = "Рекорд —",
        ["penalty drop"] = "штрафной удар",
        ["HOLE IN ONE!"] = "С ОДНОГО УДАРА!",
        ["EAGLE!"] = "ИГЛ!",
        ["BIRDIE!"] = "БЁРДИ!",
        ["PAR"] = "ПАР",
        ["BOGEY"] = "БОГИ",
        ["DOUBLE BOGEY"] = "ДАБЛ-БОГИ",
        ["{0} stroke · par {1}"] = "ударов: {0} · пар {1}",
        ["{0} strokes · par {1}"] = "ударов: {0} · пар {1}",
        ["ROUND COMPLETE"] = "РАУНД ЗАВЕРШЁН",
        ["{0} strokes · {1} vs par"] = "ударов: {0} · {1} к пару",

        // ---- Bug Squash
        ["Squash the sleeping bug to start · spare the ladybugs"] = "Раздавите спящего бага, чтобы начать · божьих коровок не трогайте",
        ["{0}s left · squashed {1}"] = "осталось {0} с · раздавлено {1}",
        ["{0}s left · squashed {1} · combo ×{2}"] = "осталось {0} с · раздавлено {1} · комбо ×{2}",
        ["{0} points · {1} squashed · {2} got away"] = "очков: {0} · раздавлено {1} · сбежало {2}",

        // ---- Can Knockdown
        ["Stack {0} · balls {1} · cans left {2}"] = "Пирамида {0} · мячей {1} · банок осталось {2}",
        ["Game over · grab the ball to play again"] = "Игра окончена · возьмите мяч, чтобы сыграть снова",
        ["CLEAR!"] = "ЧИСТО!",
        ["+{0} for spare balls"] = "+{0} за оставшиеся мячи",
        ["next stack"] = "следующая пирамида",
        ["{0} points · reached stack {1}"] = "очков: {0} · дошли до пирамиды {1}",

        // ---- Brick Breaker
        ["Level {0} · balls {1} · bricks {2}"] = "Уровень {0} · мячей {1} · кирпичей {2}",
        ["Level {0} · balls {1} · click the paddle to launch"] = "Уровень {0} · мячей {1} · нажмите на ракетку, чтобы запустить",
        ["Game over · click the paddle to play again"] = "Игра окончена · нажмите на ракетку, чтобы сыграть снова",
        ["{0} points · level {1}"] = "очков: {0} · уровень {1}",
        ["ball lost"] = "мяч потерян",
        ["{0} left"] = "осталось {0}",
        ["LEVEL CLEAR!"] = "УРОВЕНЬ ПРОЙДЕН!",
        ["+{0} bonus"] = "+{0} бонус",

        // ---- Bubble Pop
        ["Pop the bubble to start · smaller bubbles score more"] = "Лопните пузырь, чтобы начать · маленькие дают больше очков",
        ["Wave {0} cleared!"] = "Волна {0} пройдена!",
        ["Wave {0} · {1}s left · bubbles {2}"] = "Волна {0} · осталось {1} с · пузырей {2}",
        ["Wave {0} · {1}s left · bubbles {2} · combo ×{3}"] = "Волна {0} · осталось {1} с · пузырей {2} · комбо ×{3}",
        ["pop me"] = "лопни меня",
        ["WAVE {0}"] = "ВОЛНА {0}",
        ["WAVE CLEAR!"] = "ВОЛНА ПРОЙДЕНА!",
        ["+{0} time bonus"] = "+{0} за время",
        ["{0} points · wave {1}"] = "очков: {0} · волна {1}",

        // ---- Air Hockey
        ["First to {0} · CPU level {1} · drag your blue mallet"] = "До {0} голов · уровень компьютера {1} · двигайте синюю биту",
        ["Match over · grab your mallet for a rematch"] = "Матч окончен · возьмите биту для реванша",
        ["Wins {0}"] = "Победы {0}",
        ["GOAL!"] = "ГОЛ!",
        ["you score"] = "вы забили",
        ["CPU scores"] = "компьютер забил",
        ["Downloading version {0}…"] = "Загрузка версии {0}…",
        ["the game restarts when it is done"] = "после установки игра перезапустится",
        ["Couldn't download the update"] = "Не удалось загрузить обновление",
        ["opening the download page instead"] = "открываем страницу загрузки",
        ["Install version {0}"] = "Установить версию {0}",
        ["Reduce motion"] = "Меньше анимации",
        ["Colour-blind friendly colours"] = "Цвета для дальтоников",
        ["Accessibility"] = "Специальные возможности",
        ["Cat"] = "Кошка",
        ["Dog"] = "Собака",
        ["Duck"] = "Утка",
        ["Pet"] = "Питомец",
        ["Make {0} baskets in Hoops"] = "Забросьте {0} мячей в «Баскетболе»",
        ["Pop {0} balloons in Archery"] = "Лопните {0} шаров в «Стрельбе из лука»",
        ["Squash {0} bugs"] = "Раздавите {0} жуков",
        ["Score {0} goals in Air Hockey"] = "Забейте {0} голов в аэрохоккее",
        ["Break {0} clays"] = "Разбейте {0} тарелочек",
        ["Break {0} bricks"] = "Разбейте {0} кирпичей",
        ["Knock down {0} cans"] = "Собейте {0} банок",
        ["Pop {0} bubbles"] = "Лопните {0} пузырей",
        ["Whack {0} bugs"] = "Прихлопните {0} жуков",
        ["Play {0} holes of Mini Golf"] = "Сыграйте {0} лунок в мини-гольф",
        ["Make {0} perfect drops in Tower Stack"] = "Сделайте {0} идеальных бросков в «Башне»",
        ["Knock down {0} blocks with the Slingshot"] = "Собейте {0} блоков из рогатки",
        ["Drop {0} Plinko discs"] = "Бросьте {0} фишек в «Плинко»",
        ["Swish {0} shots in Hoops"] = "Забросьте {0} чистых мячей в «Баскетболе»",
        ["Capture {0} pieces in Checkers"] = "Возьмите {0} шашек",
        ["Capture {0} pieces in Chess"] = "Возьмите {0} фигур в шахматах",
        ["Sink {0} ships in Sea Battle"] = "Потопите {0} кораблей в «Морском бое»",
        ["Daily challenge done!"] = "Задание дня выполнено!",
        ["{0} days in a row"] = "{0} дней подряд",
        ["come back tomorrow for a new one"] = "завтра будет новое",
        ["Today: {0} ({1}/{2})"] = "Сегодня: {0} ({1}/{2})",
        ["{0} · streak {1}"] = "{0} · серия {1}",
        ["Daily player"] = "Каждый день",
        ["Finish a daily challenge"] = "Выполните задание дня",
        ["Seven in a row"] = "Семь подряд",
        ["Finish the daily challenge 7 days in a row"] = "Выполняйте задание дня 7 дней подряд",
        ["Resumed"] = "Продолжаем",
        ["{0} · Claude worked {1}, you played {2}"] = "{0} · Claude работал {1}, вы играли {2}",
        ["PAUSED"] = "ПАУЗА",
        ["click the game to resume"] = "нажмите на игру, чтобы продолжить",
        ["Pause the game when Claude finishes or needs you"] = "Ставить игру на паузу, когда Claude закончил или ждёт вас",
        ["Shortcuts"] = "Горячие клавиши",
        ["Modifier keys"] = "Клавиши-модификаторы",
        ["Show or hide the overlay"] = "Показать или скрыть оверлей",
        ["Save"] = "Сохранить",
        ["Defaults"] = "По умолчанию",
        ["Use three different letters, A to Z."] = "Выберите три разные буквы от A до Z.",
        ["Saved: {0}. They take effect the next time Desk Arcade starts."] = "Сохранено: {0}. Сочетания заработают при следующем запуске Desk Arcade.",
        ["Saved: {0}"] = "Сохранено: {0}",
        ["Saved, but another app already uses one of these ({0}). Try other letters or keys."] = "Сохранено, но одно из сочетаний уже занято другой программой ({0}). Попробуйте другие буквы или клавиши.",
        ["Shortcuts…"] = "Горячие клавиши…",
        ["Race {0}: start a round and they start too"] = "Гонка с {0}: начните раунд — соперник начнёт тоже",
        ["{0}: {1}{2}"] = "{0}: {1}{2}",
        ["done"] = "готово",
        ["DEAD HEAT"] = "НИЧЬЯ",
        ["YOU WIN THE RACE!"] = "ВЫ ВЫИГРАЛИ ГОНКУ!",
        ["{0} WINS THE RACE"] = "{0} ВЫИГРЫВАЕТ ГОНКУ",
        ["{0} – {1}"] = "{0} – {1}",
        ["H-O-R-S-E over · grab the ball for a rematch"] = "H-O-R-S-E окончена · возьмите мяч, чтобы сыграть ещё",
        ["Match the shot from the marked spot, or take a letter"] = "Повторите бросок с отмеченного места, иначе получите букву",
        ["{0} has to match your shot"] = "{0} должен повторить ваш бросок",
        ["H-O-R-S-E · set a shot from anywhere"] = "H-O-R-S-E · бросайте откуда угодно",
        ["H-O-R-S-E · {0} is setting a shot"] = "H-O-R-S-E · {0} задаёт бросок",
        ["shoot from here"] = "бросайте отсюда",
        ["{0}'s shot"] = "бросает {0}",
        ["shoot from the marked spot"] = "бросайте с отмеченного места",
        ["The host picks the game"] = "Игру выбирает хост",
        ["{0} is hosting"] = "{0} — хост",
        ["{0} missed — your turn to set"] = "{0} промахнулся — теперь задаёте вы",
        ["{0} made it — your turn to match"] = "{0} попал — теперь повторите вы",
        ["you take a letter"] = "вы получаете букву",
        ["{0} takes a letter"] = "{0} получает букву",
        ["grab the ball for a rematch"] = "возьмите мяч, чтобы сыграть ещё",
        ["Find games"] = "Найти игры",
        ["Looking for games on your network…"] = "Ищем игры в вашей сети…",
        ["Join"] = "Подключиться",
        ["Or join by address (ask the host for their IP):"] = "Или подключитесь по адресу (спросите у хоста его IP):",
        ["{0} · {1} · already playing"] = "{0} · {1} · уже играет",
        ["{0} · {1}"] = "{0} · {1}",
        ["No games yet. Ask your co-worker to pick Play over LAN → Host a game."] = "Игр пока нет. Попросите коллегу выбрать «Игра по сети» → «Создать игру».",
        ["Click a game to join it:"] = "Нажмите на игру, чтобы подключиться:",
        ["Couldn't search the network."] = "Не удалось выполнить поиск в сети.",
        ["That doesn't look like an address, e.g. 192.168.1.20"] = "Это не похоже на адрес, например 192.168.1.20",
        ["sent to {0}"] = "отправлено: {0}",
        ["from {0}"] = "от {0}",
        ["Find games / join by address…"] = "Найти игры / подключиться по адресу…",
        ["Send"] = "Отправить",
        ["gg"] = "gg",
        ["One more?"] = "Ещё разок?",
        ["Nice shot!"] = "Отличный удар!",
        ["Your move!"] = "Ваш ход!",
        ["Ha!"] = "Ха!",
        ["Crowned"] = "Дамка",
        ["Win a game of Checkers"] = "Выиграйте партию в шашки",
        ["Checkmate"] = "Шах и мат",
        ["Win a game of Chess"] = "Выиграйте партию в шахматы",
        ["Four in a row"] = "Четыре в ряд",
        ["Win a game of Connect Four"] = "Выиграйте в «Четыре в ряд»",
        ["Three in a row"] = "Три в ряд",
        ["Win a game of Tic-tac-toe"] = "Выиграйте в крестики-нолики",
        ["Admiral"] = "Адмирал",
        ["Win a game of Sea Battle"] = "Выиграйте в морской бой",
        ["Office rival"] = "Соперник по офису",
        ["Beat a co-worker over the LAN"] = "Обыграйте коллегу по сети",
        ["Sea Battle"] = "Морской бой",
        ["click the enemy grid to start, then fire — a hit shoots again"] = "нажмите на поле противника, чтобы начать, затем стреляйте — попадание даёт ещё выстрел",
        ["Waiting for {0} to get ready…"] = "Ждём, пока {0} приготовится…",
        ["Click your grid to move your ships · click the enemy grid to start"] = "Нажмите на своё поле, чтобы переставить корабли · на поле противника — чтобы начать",
        ["Game over · click a grid for a rematch"] = "Игра окончена · нажмите на поле, чтобы сыграть ещё",
        ["Your shot · click the enemy grid · a hit shoots again"] = "Ваш выстрел · нажмите на поле противника · попадание даёт ещё выстрел",
        ["{0} is aiming…"] = "{0} целится…",
        ["SUNK!"] = "ПОТОПЛЕН!",
        ["Ship lost"] = "Корабль потерян",
        ["click a grid for a rematch"] = "нажмите на поле, чтобы сыграть ещё",
        ["Your fleet"] = "Ваш флот",
        ["Enemy waters"] = "Воды противника",
        ["Your move · click a square · right-drag moves the board"] = "Ваш ход · нажмите на клетку · правой кнопкой можно сдвинуть доску",
        ["Tic-tac-toe"] = "Крестики-нолики",
        ["Connect Four"] = "Четыре в ряд",
        ["The board is full"] = "Доска заполнена",
        ["click a column to drop a disc — four in a row wins"] = "нажмите на столбец, чтобы бросить фишку — побеждают четыре в ряд",
        ["click a square — three in a row wins"] = "нажмите на клетку — побеждают три в ряд",
        ["Chess"] = "Шахматы",
        ["Stalemate"] = "Пат",
        ["50 moves without a capture or pawn move"] = "50 ходов без взятий и ходов пешкой",
        ["Not enough pieces to mate"] = "Недостаточно фигур для мата",
        ["15 moves without a capture or a man moving"] = "15 ходов без взятий и ходов простыми",
        ["several ways lead there · click each landing on the way"] = "несколько путей ведут туда · нажимайте на каждое поле по пути",
        ["DRAW"] = "НИЧЬЯ",
        ["40 moves without a capture · click the board for a rematch"] = "40 ходов без взятий · нажмите на доску, чтобы сыграть ещё",
        ["Checkers"] = "Шашки",
        ["click a piece, then the square it should move to"] = "нажмите на шашку, затем на клетку, куда её поставить",
        ["Game over · click the board for a rematch"] = "Партия окончена · нажмите на доску, чтобы сыграть ещё",
        ["Your move · click a piece, then where it goes · right-drag moves the board"] = "Ваш ход · нажмите на шашку, затем на клетку · правой кнопкой можно сдвинуть доску",
        ["{0} is thinking…"] = "{0} думает…",
        ["DOUBLE JUMP!"] = "ДВЕ ЗА ХОД!",
        ["TRIPLE JUMP!"] = "ТРИ ЗА ХОД!",
        ["vs {0}"] = "против {0}",
        ["click the board for a rematch"] = "нажмите на доску, чтобы сыграть ещё",
        ["Play over LAN"] = "Игра по сети",
        ["Host a game"] = "Создать игру",
        ["Join a game"] = "Присоединиться",
        ["Leave"] = "Выйти",
        ["Not connected"] = "Нет подключения",
        ["Can't host"] = "Не удалось создать игру",
        ["UDP port {0} is in use"] = "UDP-порт {0} занят",
        ["Waiting for a player to join…"] = "Ждём второго игрока…",
        ["Looking for a host…"] = "Ищем игру…",
        ["Playing with {0}"] = "Играете с {0}",
        ["Connected"] = "Подключено",
        ["Hosting"] = "Игра создана",
        ["CPU"] = "Компьютер",
        ["First to {0} · vs {1} over LAN · drag your blue mallet"] = "До {0} голов · против {1} по сети · тяните синюю биту",
        ["{0} scores"] = "{0} забивает",
        ["{0}–{1} vs {2}"] = "{0}–{1} · против {2}",
        ["{0} WINS"] = "{0} ПОБЕЖДАЕТ",
        ["YOU  {0} : {1}  {2}"] = "ВЫ  {0} : {1}  {2}",
        ["YOU WIN!"] = "ВЫ ПОБЕДИЛИ!",
        ["CPU WINS"] = "ПОБЕДИЛ КОМПЬЮТЕР",
        ["{0}–{1} · the CPU gets faster"] = "{0}–{1} · компьютер становится быстрее",
        ["{0}–{1} · grab your mallet for a rematch"] = "{0}–{1} · возьмите биту для реванша",
        ["YOU  {0} : {1}  CPU"] = "ВЫ  {0} : {1}  КОМП",

        // ---- Whack-a-Bug
        ["{0}s left · whacked {1}"] = "осталось {0} с · прихлопнуто {1}",
        ["Whack the sleepy bug to start · spare the ladybugs"] = "Прихлопните сонного бага, чтобы начать · божьих коровок не трогайте",
        ["{0} points · {1} whacked"] = "очков: {0} · прихлопнуто {1}",

        // ---- Darts
        ["Darts"] = "Дартс",
        ["hold on the board to aim, let go to throw — finish on a double"] = "зажмите на мишени, чтобы прицелиться, отпустите, чтобы бросить — закончите удвоением",
        ["Hold on the board to aim, let go to throw · finish on a double"] = "Зажмите на мишени, чтобы прицелиться, отпустите, чтобы бросить · финиш удвоением",
        ["Best {0} darts"] = "Рекорд: {0} дрот.",
        ["Game shot in {0} darts · click the board for a new leg"] = "Лег закрыт за {0} дрот. · нажмите на мишень для новой партии",
        ["Dart {0} of 3 · {1} this turn"] = "Дротик {0} из 3 · за подход {1}",
        ["Miss"] = "Мимо",
        ["BULL"] = "БУЛЛ",
        ["BUST"] = "ПЕРЕБОР",
        ["back to {0}"] = "снова {0}",
        ["GAME SHOT!"] = "ЛЕГ ЗАКРЫТ!",
        ["{0} darts"] = "Дротиков: {0}",
        ["{0} darts · new best!"] = "Дротиков: {0} · новый рекорд!",
        ["game on!"] = "игра началась!",
        ["One hundred and eighty"] = "Сто восемьдесят",
        ["Score 180 with three darts"] = "Наберите 180 очков тремя дротиками",
        ["Checked out"] = "Точный финиш",
        ["Finish 5 games of 501"] = "Закончите 5 партий в 501",
        ["Hit {0} trebles in Darts"] = "Попадите в утроение в дартсе {0} раз",

        // ---- Clay Shooting
        ["Click the trap machine to start · shoot the clays"] = "Нажмите на машинку, чтобы начать · стреляйте по тарелкам",
        ["click to start"] = "нажмите, чтобы начать",
        ["DOUBLE!"] = "ДУПЛЕТ!",
        ["Last round {0}/{1} · click the trap to go again"] = "Прошлый раунд {0}/{1} · нажмите на машинку, чтобы начать снова",
        ["Pull {0}/{1} · hits {2}"] = "Бросок {0}/{1} · попаданий {2}",
        ["still rising"] = "ещё на подъёме",
        ["{0} of {1} clays hit · {2} points"] = "попаданий {0} из {1} · очков {2}",

        // ---- Plinko
        ["click to drop · right-drag to move"] = "нажмите, чтобы бросить · правой кнопкой переместить",
        ["click for a new round"] = "нажмите для нового раунда",
        ["Round over · click the drop strip to play again"] = "Раунд окончен · нажмите на полосу, чтобы сыграть снова",
        ["Discs {0} · jackpots {1}"] = "Дисков {0} · джекпотов {1}",
        ["{0} points · {1} jackpots"] = "очков: {0} · джекпотов {1}",
        ["JACKPOT!"] = "ДЖЕКПОТ!",

        // ---- Tower Stack
        ["Height {0} · click the block to drop it"] = "Высота {0} · нажмите на блок, чтобы сбросить",
        ["Game over · click the block to play again"] = "Игра окончена · нажмите на блок, чтобы сыграть снова",
        ["PERFECT!"] = "ИДЕАЛЬНО!",
        ["wider block"] = "блок шире",
        ["Height {0}"] = "Высота {0}",

        // ---- Slingshot
        ["Slingshot"] = "Рогатка",
        ["drag back from the slingshot and let go — knock the tower down"] = "оттяните рогатку и отпустите — свалите башню",
        ["Tower {0} · stones {1} · blocks {2}"] = "Башня {0} · камней {1} · блоков {2}",
        ["Game over · pull the stone to play again"] = "Игра окончена · оттяните камень, чтобы сыграть снова",
        ["+{0} · spare stones {1}"] = "+{0} · осталось камней {1}",
        ["next tower"] = "следующая башня",
        ["Tower collapsed"] = "Башня рухнула",
        ["building a new one"] = "строится новая",
        ["{0} points · tower {1}"] = "очков: {0} · башня {1}",

        // ---- Desktop Pet
        ["Desktop Pet"] = "Питомец",
        ["click the pet to pet it — drag to carry and throw it"] = "нажмите на питомца, чтобы погладить — перетащите, чтобы нести и бросить",
        ["Sleeping · click to wake"] = "Спит · нажмите, чтобы разбудить",
        ["Wheee! · let go to throw"] = "Уиии! · отпустите, чтобы бросить",
        ["Wheee!"] = "Уиии!",
        ["Wants attention · click to pet"] = "Хочет внимания · нажмите, чтобы погладить",
        ["Grooming"] = "Умывается",
        ["Hunting the cursor"] = "Охотится на курсор",
        ["Sleepy"] = "Хочет спать",
        ["Zoomies!"] = "Носится как угорелый!",
        ["Exploring the window tops"] = "Гуляет по верхам окон",
        ["Click to pet · drag to carry"] = "Нажмите, чтобы погладить · перетащите, чтобы нести",
        ["Pets {0}"] = "Поглажено {0}",
        ["z z"] = "z z",

        // ---- Paper Toss
        ["Paper Toss"] = "Бумажка в корзину",
        ["flick the paper ball into the bin — mind the fan"] = "бросьте бумажный комок в корзину — следите за вентилятором",
        ["Grab the paper ball and flick it into the bin"] = "Схватите бумажный комок и бросьте его в корзину",
        ["Streak {0} · mind the wind"] = "Серия {0} · учитывайте ветер",
        ["Wind {0}"] = "Ветер {0}",
        ["In!"] = "Есть!",
        ["Swish!"] = "Чисто!",
        ["Missed!"] = "Мимо!",
        ["Wastebasket pro"] = "Мастер корзины",
        ["Score 10 in one run"] = "Наберите 10 очков за одну попытку",
        ["Clean throw"] = "Чистый бросок",
        ["Toss 25 swishes into the bin"] = "Забросьте в корзину 25 бумажек, не задев края",
        ["Toss {0} paper balls into the bin"] = "Забросьте в корзину {0} бумажных комков",

        // ---- achievements
        ["Coffee break"] = "Кофе-брейк",
        ["Play for 30 minutes in total"] = "Сыграйте в сумме 30 минут",
        ["Marathon"] = "Марафон",
        ["Play for 5 hours in total"] = "Сыграйте в сумме 5 часов",
        ["Explorer"] = "Исследователь",
        ["Play 6 different games"] = "Сыграйте в 6 разных игр",
        ["Pair programmer"] = "Парный программист",
        ["Be playing when Claude finishes 10 times"] = "Играйте в момент, когда Claude заканчивает, 10 раз",
        ["Hundred baskets"] = "Сотня попаданий",
        ["Score 100 baskets"] = "Забросьте 100 мячей",
        ["Nothing but net"] = "Только сетка",
        ["Score 25 swishes"] = "Забросьте 25 чистых мячей",
        ["Unstoppable"] = "Неудержимый",
        ["Make 10 baskets in a row"] = "Забросьте 10 мячей подряд",
        ["Bullseye"] = "В яблочко",
        ["Hit 10 bullseyes"] = "Попадите в яблочко 10 раз",
        ["Party pooper"] = "Зануда",
        ["Pop 50 balloons"] = "Лопните 50 шариков",
        ["Sharpshooter"] = "Меткий стрелок",
        ["Score 80 points in one round"] = "Наберите 80 очков за раунд",
        ["Keepy-uppy pro"] = "Мастер чеканки",
        ["Score 25 points in one run"] = "Наберите 25 очков за одну попытку",
        ["Star catcher"] = "Ловец звёзд",
        ["Catch 20 stars"] = "Поймайте 20 звёзд",
        ["Hole in one"] = "С одного удара",
        ["Sink a hole in one"] = "Загоните мяч в лунку с одного удара",
        ["Course regular"] = "Завсегдатай поля",
        ["Finish 50 holes"] = "Пройдите 50 лунок",
        ["Under par"] = "Ниже пара",
        ["Finish a round under par"] = "Завершите раунд ниже пара",
        ["Exterminator"] = "Истребитель",
        ["Squash 200 bugs"] = "Раздавите 200 багов",
        ["Combo breaker"] = "Мастер комбо",
        ["Reach a ×4 combo"] = "Наберите комбо ×4",
        ["Zero bugs"] = "Ноль багов",
        ["Score 60 points in one round"] = "Наберите 60 очков за раунд",
        ["Tin smasher"] = "Гроза банок",
        ["Knock down 100 cans"] = "Сбейте 100 банок",
        ["Fairground champion"] = "Чемпион ярмарки",
        ["Reach stack 5"] = "Дойдите до 5-й пирамиды",
        ["Demolition crew"] = "Бригада сноса",
        ["Break 500 bricks"] = "Разбейте 500 кирпичей",
        ["Wall breaker"] = "Разрушитель стен",
        ["Reach level 4"] = "Дойдите до 4-го уровня",
        ["Bubble wrap"] = "Пупырка",
        ["Pop 300 bubbles"] = "Лопните 300 пузырей",
        ["Wave rider"] = "Покоритель волн",
        ["Reach wave 5"] = "Дойдите до 5-й волны",
        ["First win"] = "Первая победа",
        ["Beat the CPU"] = "Победите компьютер",
        ["Sniper"] = "Снайпер",
        ["Score 50 goals"] = "Забейте 50 голов",
        ["Champion"] = "Чемпион",
        ["Beat CPU level 5"] = "Победите компьютер 5-го уровня",
        ["Best friends"] = "Лучшие друзья",
        ["Pet your desktop pet 50 times"] = "Погладьте питомца 50 раз",
        ["Taxi"] = "Такси",
        ["Carry your pet 10 times"] = "Перенесите питомца 10 раз",
        ["Skyscraper"] = "Небоскрёб",
        ["Build a tower 15 blocks high"] = "Постройте башню из 15 блоков",
        ["Perfectionist"] = "Перфекционист",
        ["Make 10 perfect drops"] = "Сделайте 10 идеальных сбросов",
        ["Wrecking ball"] = "Шар для сноса",
        ["Knock down 200 blocks"] = "Сбейте 200 блоков",
        ["Clean sweep"] = "Подчистую",
        ["Clear 10 towers"] = "Разрушьте 10 башен",
        ["Bug whacker"] = "Мухобойка",
        ["Whack 200 bugs"] = "Прихлопните 200 багов",
        ["Lightning hands"] = "Молниеносные руки",
        ["Score 50 points in one round"] = "Наберите 50 очков за раунд",
        ["Clay breaker"] = "Гроза тарелок",
        ["Hit 100 clay targets"] = "Разбейте 100 тарелок",
        ["Double trouble"] = "Дуплет",
        ["Hit two targets with one shot"] = "Попадите в две мишени одним выстрелом",
        ["Jackpot"] = "Джекпот",
        ["Land 5 discs in the jackpot slot"] = "Попадите диском в джекпот 5 раз",
        ["Disc dropper"] = "Метатель дисков",
        ["Drop 100 discs"] = "Бросьте 100 дисков",

        // 1.5: duels, Pong, series, office leaderboard, themes, pets, breaks
        ["A TIE"] = "НИЧЬЯ",
        ["After {0} minutes of play"] = "Через {0} минут игры",
        ["Air Hockey wins"] = "Победы в аэрохоккее",
        ["Arrow {0}/{1} vs {2} · your shot · wind {3}"] = "Стрела {0}/{1} против {2} · ваш выстрел · ветер {3}",
        ["Baskets"] = "Попадания",
        ["Beat the Pong CPU at level 5"] = "Обыграйте компьютер 5-го уровня в Понг",
        ["Best hoops streak"] = "Лучшая серия в баскетболе",
        ["Break reminder"] = "Напоминание о перерыве",
        ["Bugs squashed"] = "Раздавлено жуков",
        ["Bunny"] = "Кролик",
        ["Classic"] = "Классика",
        ["Claude is done · back to work"] = "Claude закончил · за работу",
        ["Duelist"] = "Дуэлянт",
        ["First to {0} vs {1} · drag your paddle"] = "До {0} против {1} · двигайте ракетку",
        ["First to {0} · CPU level {1} · drag your paddle"] = "До {0} · уровень компьютера {1} · двигайте ракетку",
        ["First to {0} · best of 3 vs {1} · drag your blue mallet"] = "До {0} · серия до двух побед против {1} · двигайте синюю биту",
        ["Fox"] = "Лиса",
        ["Halloween"] = "Хэллоуин",
        ["Hole {0} halved"] = "Лунка {0} вничью",
        ["Hole {0}/{1} vs {2} · your putt"] = "Лунка {0}/{1} против {2} · ваш удар",
        ["Hole {0}/{1} · you're in · {2} is still putting"] = "Лунка {0}/{1} · вы в лунке · {2} ещё бьёт",
        ["Hole {0}/{1} · {2} is putting"] = "Лунка {0}/{1} · бьёт {2}",
        ["LAN wins"] = "Победы по сети",
        ["MATCH HALVED"] = "НИЧЬЯ",
        ["Match over · grab your paddle for a rematch"] = "Матч окончен · возьмите ракетку для реванша",
        ["Match over · pull the bow for a rematch"] = "Матч окончен · натяните лук для реванша",
        ["Match over · pull the bow to ask {0} for a rematch"] = "Матч окончен · натяните лук, чтобы предложить {0} реванш",
        ["Match over · putt to ask {0} for a rematch"] = "Матч окончен · ударьте, чтобы предложить {0} реванш",
        ["Match over · putt to play again"] = "Матч окончен · ударьте, чтобы сыграть ещё",
        ["Match play"] = "Матчевая игра",
        ["Minutes played"] = "Минут в игре",
        ["Neon"] = "Неон",
        ["No scores yet today. Go play something!"] = "Сегодня очков ещё нет. Сыграйте во что-нибудь!",
        ["Off"] = "Выкл.",
        ["Office leaderboard"] = "Рейтинг офиса",
        ["Office leaderboard · today"] = "Рейтинг офиса · сегодня",
        ["Only you so far. Co-workers show up here once they share their scores too."] = "Пока только вы. Коллеги появятся здесь, когда тоже поделятся очками.",
        ["POINT!"] = "ОЧКО!",
        ["Paddle legend"] = "Легенда ракетки",
        ["Penguin"] = "Пингвин",
        ["Pong"] = "Понг",
        ["Pong wins"] = "Победы в Понг",
        ["Rally master"] = "Мастер розыгрыша",
        ["Retro"] = "Ретро",
        ["Say “back to work” when Claude is done"] = "Говорить «за работу», когда Claude закончит",
        ["Seasonal"] = "По сезону",
        ["Series winner"] = "Победитель серии",
        ["Share my scores on the local network"] = "Делиться моими очками в локальной сети",
        ["Sharing is off. Turn it on to post your scores and see everyone else's. It sends your user name and today's scores to the other computers on your local network, and nothing else."] = "Обмен выключен. Включите его, чтобы публиковать свои очки и видеть чужие. Он отправляет другим компьютерам в локальной сети только ваше имя пользователя и сегодняшние очки.",
        ["Show the leaderboard…"] = "Показать рейтинг…",
        ["Stop sharing my scores"] = "Перестать делиться очками",
        ["Tallest tower"] = "Самая высокая башня",
        ["Theme"] = "Тема",
        ["Win a Mini Golf match over the LAN"] = "Выиграйте матч в мини-гольф по сети",
        ["Win a best-of-3 series over the LAN"] = "Выиграйте серию до двух побед по сети",
        ["Win a game of Pong"] = "Выиграйте партию в Понг",
        ["Win an Archery match over the LAN"] = "Выиграйте матч по стрельбе из лука по сети",
        ["Winter"] = "Зима",
        ["YOU WIN THE MATCH!"] = "ВЫ ВЫИГРАЛИ МАТЧ!",
        ["YOU WIN THE SERIES!"] = "ВЫ ВЫИГРАЛИ СЕРИЮ!",
        ["You win hole {0}"] = "Лунка {0} ваша",
        ["You've played {0} minutes"] = "Вы играете уже {0} минут",
        ["asked {0} for a rematch"] = "{0} предложен реванш",
        ["drag your paddle up and down — get the ball past the right edge"] = "двигайте ракетку вверх и вниз — отправьте мяч за правый край",
        ["holes {0}–{1}"] = "лунки {0}–{1}",
        ["holes {0}–{1} · putt for a rematch"] = "лунки {0}–{1} · ударьте для реванша",
        ["series {0}–{1}"] = "серия {0}–{1}",
        ["the game will still be here later"] = "игра подождёт",
        ["time for a short break · stretch and look away from the screen"] = "пора сделать перерыв · потянитесь и отведите взгляд от экрана",
        ["you're in · wait for the next hole"] = "вы в лунке · ждите следующую",
        ["{0} (you)"] = "{0} (вы)",
        ["{0} WINS THE MATCH"] = "{0} ВЫИГРЫВАЕТ МАТЧ",
        ["{0} WINS THE SERIES"] = "{0} ВЫИГРЫВАЕТ СЕРИЮ",
        ["{0} is in"] = "{0} в лунке",
        ["{0} is shooting · wind {1}"] = "стреляет {0} · ветер {1}",
        ["{0} missed"] = "{0} промахнулся",
        ["{0} players sharing today · updates every 20 seconds"] = "сегодня делятся очками игроков: {0} · обновление каждые 20 секунд",
        ["{0} wins hole {1}"] = "лунка {1} за {0}",
        ["{0}'s putt"] = "бьёт {0}",
        ["{0}–{1} in matches · grab your mallet for a new series"] = "{0}–{1} по матчам · возьмите биту для новой серии",
        ["{0}–{1} vs {2} · series {3}–{4}"] = "{0}–{1} против {2} · серия {3}–{4}",
        ["{0}–{1} · grab your paddle for a rematch"] = "{0}–{1} · возьмите ракетку для реванша",
        ["{0}–{1} · pull the bow for a rematch"] = "{0}–{1} · натяните лук для реванша",
        ["{0}–{1} · series {2}–{3} · grab your mallet for the next match"] = "{0}–{1} · серия {2}–{3} · возьмите биту для следующего матча",
        ["{0}–{1} · the CPU gets sharper"] = "{0}–{1} · компьютер становится точнее",

        // 1.6: Durak, CPU levels, pet tricks
        ["(computer players fill empty seats)"] = "(свободные места займут компьютерные игроки)",
        ["A DRAW"] = "НИЧЬЯ",
        ["A draw · click New game"] = "Ничья · нажмите «Новая игра»",
        ["Beat each card (click a card on the table first to choose) or take"] = "Покройте каждую карту (сначала можно выбрать карту на столе) или возьмите",
        ["CPU difficulty"] = "Уровень компьютера",
        ["CPU {0}"] = "Компьютер {0}",
        ["Card shark"] = "Карточный шулер",
        ["Click Durak on the table to start a game"] = "Нажмите на стол, чтобы начать игру в дурака",
        ["Click to pet · right-click for a trick · drag to carry"] = "Нажмите, чтобы погладить · правый клик — трюк · перетащите, чтобы понести",
        ["Create a room"] = "Создать комнату",
        ["Done"] = "Бито",
        ["Durak"] = "Дурак",
        ["{0} with co-workers"] = "{0} с коллегами",
        ["Durak with co-workers…"] = "Дурак с коллегами…",
        ["Escape being the durak 10 times"] = "10 раз не остаться дураком",
        ["Get rid of your cards before someone else in Durak"] = "Избавьтесь от карт раньше другого игрока в дурака",
        ["IP address (optional)"] = "IP-адрес (необязательно)",
        ["In room {0} · waiting for the host to start"] = "Вы в комнате {0} · ждём, когда хост начнёт",
        ["Joining room {0}…"] = "Подключение к комнате {0}…",
        ["Leave the room"] = "Выйти из комнаты",
        ["Looking for room {0}…"] = "Ищем комнату {0}…",
        ["NOT THE FOOL!"] = "НЕ ДУРАК!",
        ["New game"] = "Новая игра",
        ["No room with that code answered. Check the code, or add the host's IP address."] = "Комната с таким кодом не ответила. Проверьте код или укажите IP-адрес хоста.",
        ["No rooms yet."] = "Комнат пока нет.",
        ["Not the fool"] = "Не дурак",
        ["Or host the game yourself:"] = "Или создайте игру сами:",
        ["Or type a room code (and the host's IP if the room doesn't show up):"] = "Или введите код комнаты (и IP-адрес хоста, если комната не видна):",
        ["Other games…"] = "Другие игры…",
        ["Play 1 computer"] = "С 1 компьютером",
        ["Play with"] = "Играть",
        ["Play with co-workers…"] = "Играть с коллегами…",
        ["Play {0} computers"] = "С компьютерами: {0}",
        ["Room {0} · {1} at the table"] = "Комната {0} · за столом: {1}",
        ["Waiting for a co-worker to join…"] = "Ждём, пока подключится коллега…",
        ["Start + 1 computer"] = "Начать + 1 компьютер",
        ["Start + {0} computers"] = "Начать + компьютеры: {0}",
        ["Room setup…"] = "Настройки комнаты…",
        ["Start with computers only"] = "Начать только с компьютерами",
        ["Rooms on your network:"] = "Комнаты в вашей сети:",
        ["Show-off"] = "Хвастунишка",
        ["Showing off"] = "Показывает трюк",
        ["Start the game"] = "Начать игру",
        ["Take"] = "Беру",
        ["That game has already started."] = "Эта игра уже началась.",
        ["That room is full."] = "Эта комната заполнена.",
        ["The last one holding cards is the durak"] = "Кто последним остался с картами — дурак",
        ["The room closed · set up a new game"] = "Комната закрылась · настройте новую игру",
        ["The room closed."] = "Комната закрылась.",
        ["Throw in a card of a rank on the table, or click Done"] = "Подкиньте карту того же достоинства или нажмите «Бито»",
        ["Two to four players on the same network. Everyone needs Desk Arcade {0} or newer."] = "От двух до четырёх игроков в одной сети. У всех должна быть Desk Arcade {0} или новее.",
        ["That room is playing another game."] = "В этой комнате играют в другую игру.",
        ["Watch your pet do 25 tricks"] = "Посмотрите 25 трюков питомца",
        ["Wins {0} · CPU {1}"] = "Победы {0} · компьютер: {1}",
        ["YOU'RE THE DURAK!"] = "ВЫ ДУРАК!",
        ["You"] = "Вы",
        ["You take the cards · the others may still throw in"] = "Вы берёте карты · остальные ещё могут подкинуть",
        ["You're in room {0} · waiting for the host to start. You can close this window."] = "Вы в комнате {0} · ждём, когда хост начнёт. Это окно можно закрыть.",
        ["You're out of cards · watching the others finish"] = "Ваши карты кончились · смотрите, как доиграют другие",
        ["You're the durak · click New game"] = "Вы дурак · нажмите «Новая игра»",
        ["Your attack on {0} · play any card"] = "Вы ходите под {0} · положите любую карту",
        ["Your room code — tell it to your co-workers:"] = "Код вашей комнаты — скажите его коллегам:",
        ["attacking"] = "ходит",
        ["better luck next deal"] = "повезёт в следующий раз",
        ["deck {0}"] = "колода {0}",
        ["defending"] = "отбивается",
        ["discarded {0}"] = "бито {0}",
        ["disconnected"] = "отключился",
        ["not allowed right now"] = "сейчас так нельзя",
        ["out"] = "вышел",
        ["play the computer, or set up a room for up to four co-workers"] = "играйте с компьютером или создайте комнату до четырёх коллег",
        ["playing"] = "идёт игра",
        ["that card can't beat any of them"] = "эта карта ничего не покрывает",
        ["the CPU goes easier: {0} · click the board for a rematch"] = "компьютер играет легче: {0} · нажмите на доску, чтобы сыграть ещё",
        ["the CPU moves up to {0}"] = "компьютер становится сильнее: {0}",
        ["the last cards went out together"] = "последние карты ушли одновременно",
        ["trump {0}"] = "козырь {0}",
        ["{0} (you, host)"] = "{0} (вы, хост)",
        ["{0} attacks {1}"] = "{0} ходит под {1}",
        ["{0} is defending"] = "{0} отбивается",
        ["{0} is the durak"] = "{0} — дурак",
        ["{0} is the durak · click New game"] = "{0} — дурак · нажмите «Новая игра»",
        ["{0} left · the computer plays for them"] = "{0} вышел · за него играет компьютер",
        ["{0} may throw in more"] = "{0} может подкинуть ещё",
        ["{0} players"] = "{0} игрока",
        ["{0} takes"] = "{0} берёт",
        ["{0} · {1} · {2}/{3} players"] = "{0} · {1} · игроков: {2}/{3}",
        ["Easy"] = "Легко",
        ["Medium"] = "Средне",
        ["Hard"] = "Сложно",
        ["Expert"] = "Эксперт",
        ["Couldn't open a room"] = "Не удалось открыть комнату",
        ["{0} is back"] = "{0} вернулся",

        // ---- Fishing
        ["Fishing"] = "Рыбалка",
        ["drag back from the rod to cast — click when the bobber goes under, hold to reel"] =
            "потяните назад от удочки, чтобы забросить — жмите, когда поплавок уйдёт под воду, и держите, чтобы подматывать",
        ["{0}s left · caught {1}"] = "осталось {0} с · поймано {1}",
        ["Drag back from the rod tip and let go to cast"] = "Потяните назад от кончика удочки и отпустите, чтобы забросить",
        ["Perch"] = "Окунь",
        ["Carp"] = "Карп",
        ["Pike"] = "Щука",
        ["Catfish"] = "Сом",
        ["Golden Trout"] = "Золотая форель",
        ["{0} · {1} kg"] = "{0} · {1} кг",
        ["+{0} points"] = "очков: +{0}",
        ["{0} points · {1} caught"] = "очков: {0} · поймано {1}",
        ["Too soon!"] = "Рано!",
        ["you spooked it"] = "вы спугнули рыбу",
        ["Too late!"] = "Поздно!",
        ["it stole the bait · reel in"] = "рыба украла наживку · смотайте леску",
        ["Line snapped!"] = "Леска оборвалась!",
        ["it got away"] = "рыба ушла",
        ["Angler"] = "Рыболов",
        ["Catch 50 fish"] = "Поймайте 50 рыб",
        ["Golden catch"] = "Золотой улов",
        ["Catch a golden trout"] = "Поймайте золотую форель",
        ["Catch {0} fish"] = "Поймайте рыб: {0}",
        // ---- Bowling
        ["Bowling"] = "Боулинг",
        ["drag back from the ball and let go — knock all ten pins down"] = "оттяните шар назад и отпустите — собейте все десять кеглей",
        ["Drag back from the ball and let go to bowl"] = "Чтобы бросить, оттяните шар назад и отпустите",
        ["Game over · drag back from the ball to bowl again"] = "Игра окончена · оттяните шар, чтобы сыграть ещё",
        ["Frame {0} · ball {1} · pins {2}"] = "Фрейм {0} · бросок {1} · кеглей {2}",
        ["STRIKE!"] = "СТРАЙК!",
        ["TURKEY!"] = "ИНДЕЙКА!",
        ["three strikes in a row"] = "три страйка подряд",
        ["SPARE!"] = "СПЭР!",
        ["Gutter"] = "В жёлоб",
        ["split"] = "сплит",
        ["Turkey"] = "Индейка",
        ["Bowl three strikes in a row"] = "Выбейте три страйка подряд",
        ["League night"] = "Вечер лиги",
        ["Score 150 in one game"] = "Наберите 150 очков за одну игру",
        ["Knock down {0} pins in Bowling"] = "Собейте {0} кеглей в боулинге",

        // ---- Pool
        ["Pool"] = "Бильярд",
        ["drag back from the cue ball to shoot — pot every ball in as few shots as you can"] = "оттяните биток назад, чтобы ударить — забейте все шары за как можно меньшее число ударов",
        ["Shots {0} · balls left {1}"] = "Ударов {0} · осталось шаров {1}",
        ["Cleared in {0} shots · press the cue ball to rack again"] = "Стол очищен за {0} ударов · нажмите на биток, чтобы расставить заново",
        ["{0} balls in one shot!"] = "{0} шара одним ударом!",
        ["Scratch +1"] = "Биток в лузе +1",
        ["CLEARED in {0} shots"] = "ОЧИЩЕНО ЗА {0} УДАРОВ",
        ["Table cleared"] = "Стол чист",
        ["Clear the pool table"] = "Очистите бильярдный стол",
        ["Hat trick"] = "Хет-трик",
        ["Pot 3 balls with one shot"] = "Забейте 3 шара одним ударом",
        ["Pot {0} balls in Pool"] = "Забейте {0} шаров в бильярде",
        // memory
        ["Memory"] = "Мемори",
        ["Click a card to flip it · find all the pairs"] = "Нажмите на карту, чтобы открыть её · найдите все пары",
        ["Moves {0} · pairs left {1}"] = "Ходов {0} · осталось пар {1}",
        ["All pairs in {0} moves · click a card to deal again"] = "Все пары найдены, ходов: {0} · нажмите на карту, чтобы раздать заново",
        ["Fewest moves {0}"] = "Рекорд ходов {0}",
        ["ALL PAIRS!"] = "ВСЕ ПАРЫ!",
        ["{0} moves · {1}s"] = "ходов: {0} · {1} с",
        ["flip two cards at a time — find all the pairs"] = "открывайте по две карты — найдите все пары",
        ["Total recall"] = "Абсолютная память",
        ["Clear a Memory board"] = "Найдите все пары в «Мемори»",
        ["Matchmaker"] = "Мастер пар",
        ["Find 100 pairs"] = "Найдите 100 пар",
        ["Find {0} pairs in Memory"] = "Найдите пары в «Мемори»: {0}",
        // solitaire
        ["Solitaire"] = "Пасьянс",
        ["Click the stock to turn a card · click or drag cards to move them"] = "Нажмите на колоду, чтобы открыть карту · нажимайте на карты или перетаскивайте их",
        ["Moves {0} · {1}"] = "Ходов {0} · {1}",
        ["Solved in {0} moves · New deal plays again"] = "Разложен за {0} ходов · «Новая игра» начнёт заново",
        ["New deal"] = "Новая игра",
        ["Sure?"] = "Точно?",
        ["Undo"] = "Отменить",
        ["SOLVED!"] = "РАЗЛОЖЕН!",
        ["{0} moves · {1}"] = "{0} ходов · {1}",
        ["click the stock to turn a card — click or drag cards onto the piles"] = "нажмите на колоду, чтобы открыть карту — нажимайте на карты или перетаскивайте их в стопки",
        ["Patience"] = "Терпение",
        ["Solve a game of Solitaire"] = "Разложите пасьянс",
        ["Patience of a saint"] = "Ангельское терпение",
        ["Solve 10 games of Solitaire"] = "Разложите пасьянс 10 раз",
        ["Homeward bound"] = "Домой",
        ["Send 500 cards home"] = "Отправьте домой 500 карт",
        ["Send {0} cards home in Solitaire"] = "Отправьте домой {0} карт в «Пасьянсе»",
        // last card
        ["Last Card"] = "Последняя карта",
        ["Last Card with co-workers…"] = "«Последняя карта» с коллегами…",
        ["Click Last Card on the table to start a game"] = "Нажмите «Последняя карта» на столе, чтобы начать игру",
        ["Match the colour or the number · the first to play their last card wins"] = "Подбирайте цвет или число · выигрывает тот, кто первым сыграет последнюю карту",
        ["match the colour or the number — say “last card” when you're down to one"] = "подбирайте цвет или число — скажите «последняя карта», когда останется одна",
        ["You went out first · click New game"] = "Вы выиграли · нажмите «Новая игра»",
        ["{0} went out first · click New game"] = "Победа: {0} · нажмите «Новая игра»",
        ["{0}'s turn"] = "Ходит {0}",
        ["Pick a colour for your wild card"] = "Выберите цвет для джокера",
        ["Play the card you drew, or pass"] = "Сыграйте взятую карту или пасуйте",
        ["Your turn · play on the {0} {1}, or draw from the pile"] = "Ваш ход · кладите на {0} {1} или возьмите из колоды",
        ["Skip"] = "Пропуск",
        ["Reverse"] = "Разворот",
        ["Wild"] = "Джокер",
        ["You forgot to say last card!"] = "Вы не сказали «последняя карта»!",
        ["{0} forgot to say last card!"] = "{0}: «последняя карта» не сказана!",
        ["+2 cards"] = "+2 карты",
        ["first to play their last card"] = "вы первым сыграли последнюю карту",
        ["playing…"] = "ходит…",
        ["LAST CARD!"] = "ПОСЛЕДНЯЯ КАРТА!",
        ["Last card!"] = "Последняя карта!",
        ["pile {0}"] = "колода {0}",
        ["Pass"] = "Пас",
        ["red"] = "красный",
        ["yellow"] = "жёлтый",
        ["green"] = "зелёный",
        ["blue"] = "синий",
        ["Out first"] = "Первым на выход",
        ["Win a game of Last Card"] = "Выиграйте партию в «Последнюю карту»",
        ["Empty-handed"] = "С пустыми руками",
        ["Win 10 games of Last Card"] = "Выиграйте 10 партий в «Последнюю карту»",
        ["No hard feelings"] = "Ничего личного",
        ["Play 20 Wild Draw Fours"] = "Сыграйте 20 джокеров «+4»",
        ["Play {0} cards in Last Card"] = "Сыграйте {0} карт в «Последней карте»",
        // interns
        ["Interns"] = "Стажёры",
        ["pick a tool, then click an intern — get enough of them to the exit"] = "выберите инструмент и нажмите на стажёра — доведите достаточно стажёров до выхода",
        ["Level {0} · save {1} of {2} · click the hatch to open it"] = "Уровень {0} · спасите {1} из {2} · нажмите на люк, чтобы открыть",
        ["Level {0} · out {1}/{2} · lost {3} · {4}s left"] = "Уровень {0} · вышло {1}/{2} · потеряно {3} · осталось {4} с",
        ["Level {0} cleared · click the hatch for the next one"] = "Уровень {0} пройден · нажмите на люк для следующего",
        ["Saved {0} of {1} needed · click the hatch to try again"] = "Спасено {0} из нужных {1} · нажмите на люк, чтобы попробовать снова",
        ["Best level {0}"] = "Лучший уровень {0}",
        ["EVERYONE MADE IT!"] = "ДОШЛИ ВСЕ!",
        ["LEVEL {0} CLEARED"] = "УРОВЕНЬ {0} ПРОЙДЕН",
        ["{0} of {1} saved · {2} needed"] = "спасено {0} из {1} · нужно {2}",
        ["NOT ENOUGH"] = "НЕДОСТАТОЧНО",
        ["none left"] = "не осталось",
        ["not now"] = "не сейчас",
        ["EXIT"] = "ВЫХОД",
        ["click to try again"] = "нажмите, чтобы попробовать снова",
        ["click for the next level"] = "нажмите для следующего уровня",
        ["click to open"] = "нажмите, чтобы открыть",
        ["Umbrella {0}"] = "Зонт {0}",
        ["Blocker {0}"] = "Стоп {0}",
        ["Builder {0}"] = "Строитель {0}",
        ["Restart"] = "Заново",
        ["Onboarding"] = "Первый день",
        ["Clear the first level of Interns"] = "Пройдите первый уровень «Стажёров»",
        ["Head of department"] = "Начальник отдела",
        ["Clear level 10 of Interns"] = "Пройдите 10-й уровень «Стажёров»",
        ["Mentor"] = "Наставник",
        ["Get 100 interns to the exit"] = "Доведите до выхода 100 стажёров",
        ["Nobody left behind"] = "Никого не бросили",
        ["Save every intern on a level"] = "Спасите всех стажёров на уровне",
        ["Get {0} interns to the exit"] = "Доведите до выхода {0} стажёров",
        // blockfall
        ["Blockfall"] = "Блокопад",
        ["point over the well to steer — click turns, hold drops faster, right-click drops"] = "ведите указатель над стаканом — щелчок поворачивает, удержание ускоряет, правый щелчок роняет",
        ["Game over · {0} lines · click the well to play again"] = "Игра окончена · линий: {0} · нажмите на стакан, чтобы сыграть снова",
        ["Click the well to start · click turns, right-click drops"] = "Нажмите на стакан, чтобы начать · щелчок поворачивает, правый щелчок роняет",
        ["Level {0} · lines {1}"] = "Уровень {0} · линий {1}",
        ["{0} points · {1} lines"] = "очков: {0} · линий: {1}",
        ["FOUR LINES!"] = "ЧЕТЫРЕ ЛИНИИ!",
        ["Three lines"] = "Три линии",
        ["Two lines"] = "Две линии",
        ["Level {0}"] = "Уровень {0}",
        ["Next"] = "Дальше",
        ["Lines {0}"] = "Линий {0}",
        ["Click to play again"] = "Нажмите, чтобы сыграть снова",
        ["Click to start"] = "Нажмите, чтобы начать",
        ["Four at once"] = "Сразу четыре",
        ["Clear four lines with one piece"] = "Уберите четыре линии одной фигурой",
        ["Line manager"] = "Линейный менеджер",
        ["Clear 200 lines"] = "Уберите 200 линий",
        ["Stacked"] = "Под завязку",
        ["Score 10,000 points in one game"] = "Наберите 10 000 очков за игру",
        ["Clear {0} lines in Blockfall"] = "Уберите {0} линий в «Блокопаде»",
        // codebreaker
        ["Code Breaker"] = "Взломщик кода",
        ["Check"] = "Проверить",
        ["Guess {0}/{1} · pick a colour, then click a hole"] = "Попытка {0}/{1} · выберите цвет, затем нажмите на лунку",
        ["Guess {0}/{1} · click Check"] = "Попытка {0}/{1} · нажмите «Проверить»",
        ["Code cracked · click the board for a new code"] = "Код разгадан · нажмите на доску для нового кода",
        ["Out of guesses · click the board for a new code"] = "Попытки кончились · нажмите на доску для нового кода",
        ["Fewest guesses {0}"] = "Рекорд попыток {0}",
        ["CODE CRACKED!"] = "КОД РАЗГАДАН!",
        ["{0} of {1} guesses"] = "попыток: {0} из {1}",
        ["OUT OF GUESSES"] = "ПОПЫТКИ КОНЧИЛИСЬ",
        ["here is the code · click the board for a new code"] = "вот код · нажмите на доску для нового кода",
        ["pick a colour, fill the row and click Check — a black pin is the right colour in the right place"] = "выберите цвет, заполните ряд и нажмите «Проверить» — чёрный штырёк: верный цвет на верном месте",
        ["Code cracked"] = "Код взломан",
        ["Break a code"] = "Разгадайте код",
        ["Mind reader"] = "Телепат",
        ["Break a code in 4 guesses or fewer"] = "Разгадайте код за 4 попытки или меньше",
        ["Break {0} codes in Code Breaker"] = "Разгадайте коды в «Взломщике кода»: {0}",
        // ---- Pinball
        ["Pinball"] = "Пинбол",
        ["click the ball to serve — press by a flipper to flip it, right-click flips both"] = "нажмите на шар, чтобы запустить его — нажмите у флиппера, чтобы поднять его, правая кнопка поднимает оба",
        ["Ball {0} of 3"] = "Шар {0} из 3",
        ["Ball {0} of 3 · ×{1}"] = "Шар {0} из 3 · ×{1}",
        ["Ball {0} of 3 · click the ball to serve"] = "Шар {0} из 3 · нажмите на шар, чтобы запустить",
        ["Game over · click the ball to play again"] = "Игра окончена · нажмите на шар, чтобы сыграть ещё",
        ["Drained!"] = "Шар ушёл!",
        ["×{0} multiplier"] = "множитель ×{0}",
        ["Pinball wizard"] = "Пинбольный волшебник",
        ["Score 5,000 in one game"] = "Наберите 5000 очков за одну игру",
        ["Bumper cars"] = "Автодром",
        ["Hit 500 bumpers"] = "Попадите в бамперы 500 раз",
        ["Hit {0} bumpers in Pinball"] = "Попадите в бамперы {0} раз в пинболе",
        // ---- 1.8.0: scoreboard, races against the computer, movable boards
        ["Your turn"] = "Ваш ход",
        ["CPU · {0}"] = "Компьютер · {0}",
        ["Menu"] = "Меню",
        ["Hide overlay"] = "Скрыть оверлей",
        ["Drag to move"] = "Перетащите, чтобы переместить",
        ["Race the computer in solo rounds"] = "Гонка с компьютером в одиночных раундах",
        ["CPU ({0}): {1}"] = "Компьютер ({0}): {1}",
        ["CPU ({0}) is heading for {1}"] = "Компьютер ({0}) идёт к {1}",
        ["Race the computer: start a round and it plays one too"] = "Гонка с компьютером: начните раунд, и он сыграет свой",
        ["the CPU goes easier: {0}"] = "компьютер становится слабее: {0}",
        ["Pacesetter"] = "Задающий темп",
        ["Beat the computer in 10 races"] = "Обыграйте компьютер в 10 гонках",


        // ---- 1.8.0: Linux overlay
        ["No tray icon on this desktop"] = "На этом рабочем столе нет значка в трее",
        ["the ☰ button on the scoreboard has the menu"] = "меню находится под кнопкой ☰ на табло",


        // ---- 1.8.0: pets


        // ---- 1.8.0: board and turn games


        // ---- 1.8.0: duels and card tables (Durak, Last Card, Golf, Archery, Hoops)


        // ---- 1.8.0: races, part 1 (Keepy-Uppy, Bug Squash, Can Knockdown, Brick Breaker)
        ["GO!"] = "ПОЕХАЛИ!",
        ["{0} seconds · spare the ladybugs"] = "{0} секунд · божьих коровок не трогайте",


        // ---- 1.8.0: races, part 2 (Clay Shooting, Plinko, Slingshot, Darts)
        ["Click the sheet again to give up the leg"] = "Нажмите на табло ещё раз, чтобы сдать лег",
        ["LEG GIVEN UP"] = "ЛЕГ СДАН",


        // ---- 1.8.0: races, part 3 (Pool, Memory, Code Breaker, Solitaire, Interns)


        // ---- 1.8.0: animation pass (Bubbles, Whack, Tower, Bowling, Fishing, Pinball, Paper Toss, Blockfall, Hockey, Pong)


    };
}
