using System.Collections.Generic;

namespace DeskArcade;

public static partial class Strings
{
    static readonly Dictionary<string, string> RussianTable = new()
    {
        // ---- menus, notices, overlay
        ["Automatic"] = "Автоматически",
        ["Game"] = "Игра",
        ["Games"] = "Игры",
        ["General"] = "Общие",
        ["Next game"] = "Следующая игра",
        ["Bring to cursor"] = "Переместить к курсору",
        ["Stats & achievements"] = "Статистика и достижения",
        ["Stats & achievements…"] = "Статистика и достижения…",
        ["Show overlay"] = "Показать игру",
        ["Bounce on window tops"] = "Отскок от верха окон",
        ["Sound"] = "Звук",
        ["Volume"] = "Громкость",
        ["Language"] = "Язык",
        ["Alerts when Claude finishes"] = "Оповещать, когда Claude закончит",
        ["Show the overlay when Claude starts working"] = "Показывать игру, когда Claude начинает работу",
        ["Hide the overlay when Claude finishes or needs you"] = "Скрывать игру, когда Claude закончил или ждёт вас",
        ["Copy Claude Code hook config"] = "Скопировать настройки хуков Claude Code",
        ["Start when I sign in"] = "Запускать при входе в систему",
        ["Move to next monitor"] = "На следующий монитор",
        ["Check for updates"] = "Проверить обновления",
        ["Check for updates automatically"] = "Проверять обновления автоматически",
        ["Download version {0}…"] = "Скачать версию {0}…",
        ["Reset positions"] = "Сбросить расположение",
        ["Reset high scores"] = "Сбросить рекорды",
        ["Reset stats and achievements"] = "Сбросить статистику и достижения",
        ["Exit"] = "Выход",
        ["Welcome to Desk Arcade"] = "Добро пожаловать в Desk Arcade",
        ["click the scoreboard to pick a game · {0} show/hide · {1} next game"] =
            "нажмите на табло, чтобы выбрать игру · {0} показать/скрыть · {1} следующая игра",
        ["Achievement unlocked"] = "Достижение получено",
        ["Stats reset"] = "Статистика сброшена",
        ["achievements start over"] = "достижения начнутся заново",
        ["Hook config copied"] = "Настройки хуков скопированы",
        ["merge it into ~/.claude/settings.json"] = "добавьте их в ~/.claude/settings.json",
        ["Desk Arcade {0} is available"] = "Доступна Desk Arcade {0}",
        ["opening the download page"] = "открываем страницу загрузки",
        ["download it from the tray menu"] = "скачайте через меню в трее",
        ["You're up to date"] = "У вас последняя версия",
        ["version {0}"] = "версия {0}",
        ["Time played {0} · achievements {1}/{2}"] = "Время в игре {0} · достижения {1}/{2}",
        ["{0}h {1}m"] = "{0} ч {1} мин",
        ["{0}m"] = "{0} мин",

        // ---- Claude Code
        ["Claude working"] = "Claude работает",
        ["Claude working · {0}"] = "Claude работает · {0}",
        ["Claude done"] = "Claude закончил",
        ["Claude done after {0}"] = "Claude закончил за {0}",
        ["Claude is done"] = "Claude закончил",
        ["Claude needs you"] = "Claude ждёт вас",
        ["your turn!"] = "ваш ход!",
        ["check the terminal"] = "загляните в терминал",
        ["{0} · waited {1}"] = "{0} · ожидание {1}",

        // ---- game titles and switch hints
        ["Hoops"] = "Баскетбол",
        ["Archery"] = "Стрельба из лука",
        ["Keepy-Uppy"] = "Чеканка",
        ["Mini Golf"] = "Мини-гольф",
        ["Bug Squash"] = "Давилка багов",
        ["Can Knockdown"] = "Сбей банки",
        ["Brick Breaker"] = "Арканоид",
        ["Bubble Pop"] = "Лопни пузыри",
        ["Air Hockey"] = "Аэрохоккей",
        ["Clay Shooting"] = "Стендовая стрельба",
        ["Whack-a-Bug"] = "Прихлопни бага",
        ["Plinko"] = "Плинко",
        ["Tower Stack"] = "Башня",
        ["drag the ball and flick it into the hoop"] = "тяните мяч и бросайте в кольцо",
        ["drag back from the bow, release to shoot"] = "оттяните тетиву и отпустите для выстрела",
        ["click the ball to kick it — don't let it drop"] = "нажимайте на мяч, чтобы подбить — не роняйте",
        ["drag back from the ball to putt it into the cup"] = "оттяните от мяча и ударьте в лунку",
        ["squash the bugs — spare the ladybugs"] = "давите багов — божьих коровок не трогайте",
        ["throw the ball from behind the line"] = "бросайте мяч из-за линии",
        ["click the paddle to launch — the mouse steers it"] = "нажмите на ракетку, чтобы запустить — ею управляет мышь",
        ["click a bubble to split it — clear them all in time"] = "нажмите на пузырь, чтобы разделить — успейте лопнуть все",
        ["drag your mallet and score in the right-hand goal"] = "двигайте биту и забивайте в правые ворота",
        ["click the trap machine, then shoot the clays at the top of their arc"] = "нажмите на метательную машину и стреляйте по тарелкам в верхней точке",
        ["whack the bugs as they peek out — spare the ladybugs"] = "бейте багов, когда они выглядывают — божьих коровок не трогайте",
        ["click the strip to drop a disc — the gold slot is the jackpot"] = "нажмите на полосу, чтобы бросить диск — золотая ячейка это джекпот",
        ["click the sliding block to drop it — stack as high as you can"] = "нажмите на движущийся блок, чтобы сбросить — стройте как можно выше",

        // ---- shared game text
        ["Best {0}"] = "Рекорд {0}",
        ["NEW BEST!"] = "НОВЫЙ РЕКОРД!",
        ["NEW BEST ROUND!"] = "РЕКОРД РАУНДА!",
        ["GAME OVER"] = "ИГРА ОКОНЧЕНА",
        ["ROUND OVER"] = "РАУНД ОКОНЧЕН",
        ["TIME!"] = "ВРЕМЯ!",
        ["{0} points"] = "очков: {0}",
        ["that was a feature!"] = "это была фича!",

        // ---- Hoops
        ["Drag the ball, flick it into the hoop"] = "Тяните мяч и бросайте в кольцо",
        ["Streak {0} · keep going!"] = "Серия {0} · так держать!",
        ["Streak {0} · ON FIRE ×2"] = "Серия {0} · В ОГНЕ ×2",
        ["Best streak {0}"] = "Лучшая серия {0}",
        ["streak over"] = "серия прервана",
        ["DUNK!"] = "ДАНК!",
        ["SWISH!"] = "ЧИСТО!",
        ["SWISH THREE!"] = "ЧИСТЫЙ ТРЁХОЧКОВЫЙ!",
        ["THREE POINTER!"] = "ТРЁХОЧКОВЫЙ!",
        ["NICE SHOT!"] = "ОТЛИЧНЫЙ БРОСОК!",
        ["ON FIRE!"] = "В ОГНЕ!",
        ["points ×2"] = "очки ×2",
        ["MOVING HOOP!"] = "КОЛЬЦО ДВИЖЕТСЯ!",
        ["NEW BEST STREAK"] = "НОВАЯ ЛУЧШАЯ СЕРИЯ",

        // ---- Archery
        ["calm"] = "штиль",
        ["Round {0} · {1} arrows · wind {2}"] = "Раунд {0} · стрел {1} · ветер {2}",
        ["Round over · pull the bow to play again"] = "Раунд окончен · натяните лук, чтобы сыграть снова",
        ["Best round {0}"] = "Лучший раунд {0}",
        ["pull back to start a round"] = "натяните, чтобы начать раунд",
        ["{0} arrows · wind {1}"] = "стрел {0} · ветер {1}",
        ["{0} points · best {1}"] = "очков: {0} · рекорд {1}",
        ["BULLSEYE!"] = "В ЯБЛОЧКО!",
        ["GOLDEN!"] = "ЗОЛОТОЙ!",
        ["POP!"] = "ХЛОП!",

        // ---- Keepy-Uppy
        ["Click the ball to kick it up"] = "Нажмите на мяч, чтобы подбить его",
        ["Juggles {0} · grab the star!"] = "Набивания {0} · хватайте звезду!",
        ["Juggles {0} · don't let it drop"] = "Набивания {0} · не роняйте",
        ["Dropped!"] = "Упал!",

        // ---- Mini Golf
        ["Hole {0}/{1} · par {2} · stroke {3}"] = "Лунка {0}/{1} · пар {2} · удар {3}",
        ["Round done · {0} vs par · putt to play again"] = "Раунд окончен · {0} к пару · ударьте, чтобы сыграть снова",
        ["Best —"] = "Рекорд —",
        ["penalty drop"] = "штрафной удар",
        ["HOLE IN ONE!"] = "С ОДНОГО УДАРА!",
        ["EAGLE!"] = "ИГЛ!",
        ["BIRDIE!"] = "БЁРДИ!",
        ["PAR"] = "ПАР",
        ["BOGEY"] = "БОГИ",
        ["DOUBLE BOGEY"] = "ДАБЛ-БОГИ",
        ["{0} stroke · par {1}"] = "ударов: {0} · пар {1}",
        ["{0} strokes · par {1}"] = "ударов: {0} · пар {1}",
        ["ROUND COMPLETE"] = "РАУНД ЗАВЕРШЁН",
        ["{0} strokes · {1} vs par"] = "ударов: {0} · {1} к пару",

        // ---- Bug Squash
        ["Squash the sleeping bug to start · spare the ladybugs"] = "Раздавите спящего бага, чтобы начать · божьих коровок не трогайте",
        ["{0}s left · squashed {1}"] = "осталось {0} с · раздавлено {1}",
        ["{0}s left · squashed {1} · combo ×{2}"] = "осталось {0} с · раздавлено {1} · комбо ×{2}",
        ["{0} points · {1} squashed · {2} got away"] = "очков: {0} · раздавлено {1} · сбежало {2}",

        // ---- Can Knockdown
        ["Stack {0} · balls {1} · cans left {2}"] = "Пирамида {0} · мячей {1} · банок осталось {2}",
        ["Game over · grab the ball to play again"] = "Игра окончена · возьмите мяч, чтобы сыграть снова",
        ["CLEAR!"] = "ЧИСТО!",
        ["+{0} for spare balls"] = "+{0} за оставшиеся мячи",
        ["next stack"] = "следующая пирамида",
        ["{0} points · reached stack {1}"] = "очков: {0} · дошли до пирамиды {1}",

        // ---- Brick Breaker
        ["Level {0} · balls {1} · bricks {2}"] = "Уровень {0} · мячей {1} · кирпичей {2}",
        ["Level {0} · balls {1} · click the paddle to launch"] = "Уровень {0} · мячей {1} · нажмите на ракетку, чтобы запустить",
        ["Game over · click the paddle to play again"] = "Игра окончена · нажмите на ракетку, чтобы сыграть снова",
        ["{0} points · level {1}"] = "очков: {0} · уровень {1}",
        ["ball lost"] = "мяч потерян",
        ["{0} left"] = "осталось {0}",
        ["LEVEL CLEAR!"] = "УРОВЕНЬ ПРОЙДЕН!",
        ["+{0} bonus"] = "+{0} бонус",

        // ---- Bubble Pop
        ["Pop the bubble to start · smaller bubbles score more"] = "Лопните пузырь, чтобы начать · маленькие дают больше очков",
        ["Wave {0} cleared!"] = "Волна {0} пройдена!",
        ["Wave {0} · {1}s left · bubbles {2}"] = "Волна {0} · осталось {1} с · пузырей {2}",
        ["Wave {0} · {1}s left · bubbles {2} · combo ×{3}"] = "Волна {0} · осталось {1} с · пузырей {2} · комбо ×{3}",
        ["pop me"] = "лопни меня",
        ["WAVE {0}"] = "ВОЛНА {0}",
        ["WAVE CLEAR!"] = "ВОЛНА ПРОЙДЕНА!",
        ["+{0} time bonus"] = "+{0} за время",
        ["{0} points · wave {1}"] = "очков: {0} · волна {1}",

        // ---- Air Hockey
        ["First to {0} · CPU level {1} · drag your blue mallet"] = "До {0} голов · уровень компьютера {1} · двигайте синюю биту",
        ["Match over · grab your mallet for a rematch"] = "Матч окончен · возьмите биту для реванша",
        ["Wins {0}"] = "Победы {0}",
        ["GOAL!"] = "ГОЛ!",
        ["you score"] = "вы забили",
        ["CPU scores"] = "компьютер забил",
        ["Shortcuts"] = "Горячие клавиши",
        ["Modifier keys"] = "Клавиши-модификаторы",
        ["Show or hide the overlay"] = "Показать или скрыть оверлей",
        ["Save"] = "Сохранить",
        ["Defaults"] = "По умолчанию",
        ["Use three different letters, A to Z."] = "Выберите три разные буквы от A до Z.",
        ["Saved: {0}. They take effect the next time Desk Arcade starts."] = "Сохранено: {0}. Сочетания заработают при следующем запуске Desk Arcade.",
        ["Saved: {0}"] = "Сохранено: {0}",
        ["Saved, but another app already uses one of these ({0}). Try other letters or keys."] = "Сохранено, но одно из сочетаний уже занято другой программой ({0}). Попробуйте другие буквы или клавиши.",
        ["Shortcuts…"] = "Горячие клавиши…",
        ["Race {0}: start a round and they start too"] = "Гонка с {0}: начните раунд — соперник начнёт тоже",
        ["{0}: {1}{2}"] = "{0}: {1}{2}",
        ["done"] = "готово",
        ["DEAD HEAT"] = "НИЧЬЯ",
        ["YOU WIN THE RACE!"] = "ВЫ ВЫИГРАЛИ ГОНКУ!",
        ["{0} WINS THE RACE"] = "{0} ВЫИГРЫВАЕТ ГОНКУ",
        ["{0} – {1}"] = "{0} – {1}",
        ["H-O-R-S-E over · grab the ball for a rematch"] = "H-O-R-S-E окончена · возьмите мяч, чтобы сыграть ещё",
        ["Match the shot from the marked spot, or take a letter"] = "Повторите бросок с отмеченного места, иначе получите букву",
        ["{0} has to match your shot"] = "{0} должен повторить ваш бросок",
        ["H-O-R-S-E · set a shot from anywhere"] = "H-O-R-S-E · бросайте откуда угодно",
        ["H-O-R-S-E · {0} is setting a shot"] = "H-O-R-S-E · {0} задаёт бросок",
        ["shoot from here"] = "бросайте отсюда",
        ["{0}'s shot"] = "бросает {0}",
        ["shoot from the marked spot"] = "бросайте с отмеченного места",
        ["{0} made it — your turn to match"] = "{0} попал — теперь повторите вы",
        ["you take a letter"] = "вы получаете букву",
        ["{0} takes a letter"] = "{0} получает букву",
        ["grab the ball for a rematch"] = "возьмите мяч, чтобы сыграть ещё",
        ["Find games"] = "Найти игры",
        ["Looking for games on your network…"] = "Ищем игры в вашей сети…",
        ["Join"] = "Подключиться",
        ["Or join by address (ask the host for their IP):"] = "Или подключитесь по адресу (спросите у хоста его IP):",
        ["{0} · {1} · already playing"] = "{0} · {1} · уже играет",
        ["{0} · {1}"] = "{0} · {1}",
        ["No games yet. Ask your co-worker to pick Play over LAN → Host a game."] = "Игр пока нет. Попросите коллегу выбрать «Игра по сети» → «Создать игру».",
        ["Click a game to join it:"] = "Нажмите на игру, чтобы подключиться:",
        ["Couldn't search the network."] = "Не удалось выполнить поиск в сети.",
        ["That doesn't look like an address, e.g. 192.168.1.20"] = "Это не похоже на адрес, например 192.168.1.20",
        ["sent to {0}"] = "отправлено: {0}",
        ["from {0}"] = "от {0}",
        ["Find games / join by address…"] = "Найти игры / подключиться по адресу…",
        ["Send"] = "Отправить",
        ["gg"] = "gg",
        ["One more?"] = "Ещё разок?",
        ["Nice shot!"] = "Отличный удар!",
        ["Your move!"] = "Ваш ход!",
        ["Ha!"] = "Ха!",
        ["Crowned"] = "Дамка",
        ["Win a game of Checkers"] = "Выиграйте партию в шашки",
        ["Checkmate"] = "Шах и мат",
        ["Win a game of Chess"] = "Выиграйте партию в шахматы",
        ["Four in a row"] = "Четыре в ряд",
        ["Win a game of Connect Four"] = "Выиграйте в «Четыре в ряд»",
        ["Three in a row"] = "Три в ряд",
        ["Win a game of Tic-tac-toe"] = "Выиграйте в крестики-нолики",
        ["Admiral"] = "Адмирал",
        ["Win a game of Sea Battle"] = "Выиграйте в морской бой",
        ["Office rival"] = "Соперник по офису",
        ["Beat a co-worker over the LAN"] = "Обыграйте коллегу по сети",
        ["Sea Battle"] = "Морской бой",
        ["click the enemy grid to start, then fire — a hit shoots again"] = "нажмите на поле противника, чтобы начать, затем стреляйте — попадание даёт ещё выстрел",
        ["Waiting for {0} to get ready…"] = "Ждём, пока {0} приготовится…",
        ["Click your grid to move your ships · click the enemy grid to start"] = "Нажмите на своё поле, чтобы переставить корабли · на поле противника — чтобы начать",
        ["Game over · click a grid for a rematch"] = "Игра окончена · нажмите на поле, чтобы сыграть ещё",
        ["Your shot · click the enemy grid · a hit shoots again"] = "Ваш выстрел · нажмите на поле противника · попадание даёт ещё выстрел",
        ["{0} is aiming…"] = "{0} целится…",
        ["SUNK!"] = "ПОТОПЛЕН!",
        ["Ship lost"] = "Корабль потерян",
        ["click a grid for a rematch"] = "нажмите на поле, чтобы сыграть ещё",
        ["Your fleet"] = "Ваш флот",
        ["Enemy waters"] = "Воды противника",
        ["Your move · click a square · right-drag moves the board"] = "Ваш ход · нажмите на клетку · правой кнопкой можно сдвинуть доску",
        ["Tic-tac-toe"] = "Крестики-нолики",
        ["Connect Four"] = "Четыре в ряд",
        ["The board is full"] = "Доска заполнена",
        ["click a column to drop a disc — four in a row wins"] = "нажмите на столбец, чтобы бросить фишку — побеждают четыре в ряд",
        ["click a square — three in a row wins"] = "нажмите на клетку — побеждают три в ряд",
        ["Chess"] = "Шахматы",
        ["Stalemate"] = "Пат",
        ["50 moves without a capture or pawn move"] = "50 ходов без взятий и ходов пешкой",
        ["Not enough pieces to mate"] = "Недостаточно фигур для мата",
        ["40 moves without a capture"] = "40 ходов без взятий",
        ["DRAW"] = "НИЧЬЯ",
        ["40 moves without a capture · click the board for a rematch"] = "40 ходов без взятий · нажмите на доску, чтобы сыграть ещё",
        ["Checkers"] = "Шашки",
        ["click a piece, then the square it should move to"] = "нажмите на шашку, затем на клетку, куда её поставить",
        ["Game over · click the board for a rematch"] = "Партия окончена · нажмите на доску, чтобы сыграть ещё",
        ["Your move · click a piece, then where it goes · right-drag moves the board"] = "Ваш ход · нажмите на шашку, затем на клетку · правой кнопкой можно сдвинуть доску",
        ["{0} is thinking…"] = "{0} думает…",
        ["DOUBLE JUMP!"] = "ДВЕ ЗА ХОД!",
        ["TRIPLE JUMP!"] = "ТРИ ЗА ХОД!",
        ["vs {0}"] = "против {0}",
        ["click the board for a rematch"] = "нажмите на доску, чтобы сыграть ещё",
        ["Play over LAN"] = "Игра по сети",
        ["Host a game"] = "Создать игру",
        ["Join a game"] = "Присоединиться",
        ["Leave"] = "Выйти",
        ["Not connected"] = "Нет подключения",
        ["Can't host"] = "Не удалось создать игру",
        ["UDP port {0} is in use"] = "UDP-порт {0} занят",
        ["Waiting for a player to join…"] = "Ждём второго игрока…",
        ["Looking for a host…"] = "Ищем игру…",
        ["Playing with {0}"] = "Играете с {0}",
        ["Connected"] = "Подключено",
        ["Hosting"] = "Игра создана",
        ["CPU"] = "Компьютер",
        ["First to {0} · vs {1} over LAN · drag your blue mallet"] = "До {0} голов · против {1} по сети · тяните синюю биту",
        ["{0} scores"] = "{0} забивает",
        ["{0}–{1} vs {2}"] = "{0}–{1} · против {2}",
        ["{0} WINS"] = "{0} ПОБЕЖДАЕТ",
        ["YOU  {0} : {1}  {2}"] = "ВЫ  {0} : {1}  {2}",
        ["YOU WIN!"] = "ВЫ ПОБЕДИЛИ!",
        ["CPU WINS"] = "ПОБЕДИЛ КОМПЬЮТЕР",
        ["{0}–{1} · the CPU gets faster"] = "{0}–{1} · компьютер становится быстрее",
        ["{0}–{1} · grab your mallet for a rematch"] = "{0}–{1} · возьмите биту для реванша",
        ["YOU  {0} : {1}  CPU"] = "ВЫ  {0} : {1}  КОМП",

        // ---- Whack-a-Bug
        ["{0}s left · whacked {1}"] = "осталось {0} с · прихлопнуто {1}",
        ["Whack the sleepy bug to start · spare the ladybugs"] = "Прихлопните сонного бага, чтобы начать · божьих коровок не трогайте",
        ["{0} points · {1} whacked"] = "очков: {0} · прихлопнуто {1}",

        // ---- Clay Shooting
        ["Click the trap machine to start · shoot the clays"] = "Нажмите на машинку, чтобы начать · стреляйте по тарелкам",
        ["click to start"] = "нажмите, чтобы начать",
        ["DOUBLE!"] = "ДУПЛЕТ!",
        ["Last round {0}/{1} · click the trap to go again"] = "Прошлый раунд {0}/{1} · нажмите на машинку, чтобы начать снова",
        ["Pull {0}/{1} · hits {2}"] = "Бросок {0}/{1} · попаданий {2}",
        ["still rising"] = "ещё на подъёме",
        ["{0} of {1} clays hit · {2} points"] = "попаданий {0} из {1} · очков {2}",

        // ---- Plinko
        ["click to drop · right-drag to move"] = "нажмите, чтобы бросить · правой кнопкой переместить",
        ["click for a new round"] = "нажмите для нового раунда",
        ["Round over · click the drop strip to play again"] = "Раунд окончен · нажмите на полосу, чтобы сыграть снова",
        ["Discs {0} · jackpots {1}"] = "Дисков {0} · джекпотов {1}",
        ["{0} points · {1} jackpots"] = "очков: {0} · джекпотов {1}",
        ["JACKPOT!"] = "ДЖЕКПОТ!",

        // ---- Tower Stack
        ["Height {0} · click the block to drop it"] = "Высота {0} · нажмите на блок, чтобы сбросить",
        ["Game over · click the block to play again"] = "Игра окончена · нажмите на блок, чтобы сыграть снова",
        ["PERFECT!"] = "ИДЕАЛЬНО!",
        ["wider block"] = "блок шире",
        ["Height {0}"] = "Высота {0}",

        // ---- Slingshot
        ["Slingshot"] = "Рогатка",
        ["drag back from the slingshot and let go — knock the tower down"] = "оттяните рогатку и отпустите — свалите башню",
        ["Tower {0} · stones {1} · blocks {2}"] = "Башня {0} · камней {1} · блоков {2}",
        ["Game over · pull the stone to play again"] = "Игра окончена · оттяните камень, чтобы сыграть снова",
        ["+{0} · spare stones {1}"] = "+{0} · осталось камней {1}",
        ["next tower"] = "следующая башня",
        ["Tower collapsed"] = "Башня рухнула",
        ["building a new one"] = "строится новая",
        ["{0} points · tower {1}"] = "очков: {0} · башня {1}",

        // ---- Desktop Pet
        ["Desktop Pet"] = "Питомец",
        ["click the pet to pet it — drag to carry and throw it"] = "нажмите на питомца, чтобы погладить — перетащите, чтобы нести и бросить",
        ["Sleeping · click to wake"] = "Спит · нажмите, чтобы разбудить",
        ["Wheee! · let go to throw"] = "Уиии! · отпустите, чтобы бросить",
        ["Wheee!"] = "Уиии!",
        ["Wants attention · click to pet"] = "Хочет внимания · нажмите, чтобы погладить",
        ["Exploring the window tops"] = "Гуляет по верхам окон",
        ["Click to pet · drag to carry"] = "Нажмите, чтобы погладить · перетащите, чтобы нести",
        ["Pets {0}"] = "Поглажено {0}",
        ["z z"] = "z z",

        // ---- achievements
        ["Coffee break"] = "Кофе-брейк",
        ["Play for 30 minutes in total"] = "Сыграйте в сумме 30 минут",
        ["Marathon"] = "Марафон",
        ["Play for 5 hours in total"] = "Сыграйте в сумме 5 часов",
        ["Explorer"] = "Исследователь",
        ["Play 6 different games"] = "Сыграйте в 6 разных игр",
        ["Pair programmer"] = "Парный программист",
        ["Be playing when Claude finishes 10 times"] = "Играйте в момент, когда Claude заканчивает, 10 раз",
        ["Hundred baskets"] = "Сотня попаданий",
        ["Score 100 baskets"] = "Забросьте 100 мячей",
        ["Nothing but net"] = "Только сетка",
        ["Score 25 swishes"] = "Забросьте 25 чистых мячей",
        ["Unstoppable"] = "Неудержимый",
        ["Make 10 baskets in a row"] = "Забросьте 10 мячей подряд",
        ["Bullseye"] = "В яблочко",
        ["Hit 10 bullseyes"] = "Попадите в яблочко 10 раз",
        ["Party pooper"] = "Зануда",
        ["Pop 50 balloons"] = "Лопните 50 шариков",
        ["Sharpshooter"] = "Меткий стрелок",
        ["Score 80 points in one round"] = "Наберите 80 очков за раунд",
        ["Keepy-uppy pro"] = "Мастер чеканки",
        ["Score 25 points in one run"] = "Наберите 25 очков за одну попытку",
        ["Star catcher"] = "Ловец звёзд",
        ["Catch 20 stars"] = "Поймайте 20 звёзд",
        ["Hole in one"] = "С одного удара",
        ["Sink a hole in one"] = "Загоните мяч в лунку с одного удара",
        ["Course regular"] = "Завсегдатай поля",
        ["Finish 50 holes"] = "Пройдите 50 лунок",
        ["Under par"] = "Ниже пара",
        ["Finish a round under par"] = "Завершите раунд ниже пара",
        ["Exterminator"] = "Истребитель",
        ["Squash 200 bugs"] = "Раздавите 200 багов",
        ["Combo breaker"] = "Мастер комбо",
        ["Reach a ×4 combo"] = "Наберите комбо ×4",
        ["Zero bugs"] = "Ноль багов",
        ["Score 60 points in one round"] = "Наберите 60 очков за раунд",
        ["Tin smasher"] = "Гроза банок",
        ["Knock down 100 cans"] = "Сбейте 100 банок",
        ["Fairground champion"] = "Чемпион ярмарки",
        ["Reach stack 5"] = "Дойдите до 5-й пирамиды",
        ["Demolition crew"] = "Бригада сноса",
        ["Break 500 bricks"] = "Разбейте 500 кирпичей",
        ["Wall breaker"] = "Разрушитель стен",
        ["Reach level 4"] = "Дойдите до 4-го уровня",
        ["Bubble wrap"] = "Пупырка",
        ["Pop 300 bubbles"] = "Лопните 300 пузырей",
        ["Wave rider"] = "Покоритель волн",
        ["Reach wave 5"] = "Дойдите до 5-й волны",
        ["First win"] = "Первая победа",
        ["Beat the CPU"] = "Победите компьютер",
        ["Sniper"] = "Снайпер",
        ["Score 50 goals"] = "Забейте 50 голов",
        ["Champion"] = "Чемпион",
        ["Beat CPU level 5"] = "Победите компьютер 5-го уровня",
        ["Best friends"] = "Лучшие друзья",
        ["Pet your desktop pet 50 times"] = "Погладьте питомца 50 раз",
        ["Taxi"] = "Такси",
        ["Carry your pet 10 times"] = "Перенесите питомца 10 раз",
        ["Skyscraper"] = "Небоскрёб",
        ["Build a tower 15 blocks high"] = "Постройте башню из 15 блоков",
        ["Perfectionist"] = "Перфекционист",
        ["Make 10 perfect drops"] = "Сделайте 10 идеальных сбросов",
        ["Wrecking ball"] = "Шар для сноса",
        ["Knock down 200 blocks"] = "Сбейте 200 блоков",
        ["Clean sweep"] = "Подчистую",
        ["Clear 10 towers"] = "Разрушьте 10 башен",
        ["Bug whacker"] = "Мухобойка",
        ["Whack 200 bugs"] = "Прихлопните 200 багов",
        ["Lightning hands"] = "Молниеносные руки",
        ["Score 50 points in one round"] = "Наберите 50 очков за раунд",
        ["Clay breaker"] = "Гроза тарелок",
        ["Hit 100 clay targets"] = "Разбейте 100 тарелок",
        ["Double trouble"] = "Дуплет",
        ["Hit two targets with one shot"] = "Попадите в две мишени одним выстрелом",
        ["Jackpot"] = "Джекпот",
        ["Land 5 discs in the jackpot slot"] = "Попадите диском в джекпот 5 раз",
        ["Disc dropper"] = "Метатель дисков",
        ["Drop 100 discs"] = "Бросьте 100 дисков",
    };
}
