using System.Collections.Generic;

namespace DeskArcade;

public static partial class Strings
{
    static readonly Dictionary<string, string> UzbekTable = new()
    {
        // ---- menus, notices, overlay
        ["Automatic"] = "Avtomatik",
        ["Game"] = "O'yin",
        ["Games"] = "O'yinlar",
        ["General"] = "Umumiy",
        ["Next game"] = "Keyingi o'yin",
        ["Bring to cursor"] = "Kursorga olib kelish",
        ["Stats & achievements"] = "Statistika va yutuqlar",
        ["Stats & achievements…"] = "Statistika va yutuqlar…",
        ["Show overlay"] = "O'yinni ko'rsatish",
        ["Bounce on window tops"] = "Oyna tepasida sakrash",
        ["Sound"] = "Ovoz",
        ["Volume"] = "Ovoz balandligi",
        ["Language"] = "Til",
        ["Alerts when Claude finishes"] = "Claude tugatganda ogohlantirish",
        ["Show the overlay when Claude starts working"] = "Claude ishni boshlaganda o'yinni ko'rsatish",
        ["Hide the overlay when Claude finishes or needs you"] = "Claude tugatganda yoki sizni kutganda o'yinni yashirish",
        ["Copy Claude Code hook config"] = "Claude Code hook sozlamasini nusxalash",
        ["Start when I sign in"] = "Tizimga kirganda ishga tushirish",
        ["Move to next monitor"] = "Keyingi monitorga o'tkazish",
        ["Check for updates"] = "Yangilanishlarni tekshirish",
        ["Check for updates automatically"] = "Yangilanishlarni avtomatik tekshirish",
        ["Download version {0}…"] = "{0} versiyasini yuklab olish…",
        ["Reset positions"] = "Joylashuvlarni tiklash",
        ["Reset high scores"] = "Rekordlarni tozalash",
        ["Reset stats and achievements"] = "Statistika va yutuqlarni tozalash",
        ["Exit"] = "Chiqish",
        ["Welcome to Desk Arcade"] = "Desk Arcade'ga xush kelibsiz",
        ["click the scoreboard to pick a game · {0} show/hide · {1} next game"] =
            "o'yin tanlash uchun hisob taxtasini bosing · {0} ko'rsatish/yashirish · {1} keyingi o'yin",
        ["Achievement unlocked"] = "Yutuq ochildi",
        ["Stats reset"] = "Statistika tozalandi",
        ["achievements start over"] = "yutuqlar boshidan boshlanadi",
        ["Hook config copied"] = "Hook sozlamasi nusxalandi",
        ["merge it into ~/.claude/settings.json"] = "uni ~/.claude/settings.json fayliga qo'shing",
        ["Desk Arcade {0} is available"] = "Desk Arcade {0} chiqdi",
        ["opening the download page"] = "yuklab olish sahifasi ochilmoqda",
        ["download it from the tray menu"] = "uni tray menyusidan yuklab oling",
        ["You're up to date"] = "Sizda eng so'nggi versiya",
        ["version {0}"] = "versiya {0}",
        ["Time played {0} · achievements {1}/{2}"] = "O'ynalgan vaqt {0} · yutuqlar {1}/{2}",
        ["{0}h {1}m"] = "{0} soat {1} daq",
        ["{0}m"] = "{0} daq",

        // ---- Claude Code
        ["Claude working"] = "Claude ishlayapti",
        ["Claude working · {0}"] = "Claude ishlayapti · {0}",
        ["Claude done"] = "Claude tugatdi",
        ["Claude done after {0}"] = "Claude {0} da tugatdi",
        ["Claude is done"] = "Claude tugatdi",
        ["Claude needs you"] = "Claude sizni kutyapti",
        ["your turn!"] = "navbat sizda!",
        ["check the terminal"] = "terminalni tekshiring",
        ["{0} · waited {1}"] = "{0} · kutildi {1}",

        // ---- game titles and switch hints
        ["Hoops"] = "Basketbol",
        ["Archery"] = "Kamondan otish",
        ["Keepy-Uppy"] = "To'p tepish",
        ["Mini Golf"] = "Mini golf",
        ["Bug Squash"] = "Qo'ng'izlarni ezish",
        ["Can Knockdown"] = "Bankalarni urish",
        ["Brick Breaker"] = "G'isht sindirish",
        ["Bubble Pop"] = "Pufakcha yorish",
        ["Air Hockey"] = "Havo xokkeyi",
        ["Clay Shooting"] = "Nishonga otish",
        ["Whack-a-Bug"] = "Qo'ng'iz urish",
        ["Plinko"] = "Plinko",
        ["drag the ball and flick it into the hoop"] = "to'pni sudrab, halqaga otib yuboring",
        ["drag back from the bow, release to shoot"] = "kamondan orqaga torting, otish uchun qo'yib yuboring",
        ["click the ball to kick it — don't let it drop"] = "to'pni bosib tepib turing — tushirib yubormang",
        ["drag back from the ball to putt it into the cup"] = "to'pdan orqaga torting va chuqurchaga uring",
        ["squash the bugs — spare the ladybugs"] = "qo'ng'izlarni ezing — xonqizlarga tegmang",
        ["throw the ball from behind the line"] = "to'pni chiziq ortidan oting",
        ["click the paddle to launch — the mouse steers it"] = "boshlash uchun raketkani bosing — uni sichqoncha boshqaradi",
        ["click a bubble to split it — clear them all in time"] = "pufakchani bosib bo'ling — hammasini vaqtida yo'q qiling",
        ["drag your mallet and score in the right-hand goal"] = "tayoqchani sudrab, o'ngdagi darvozaga gol uring",
        ["click the trap machine, then shoot the clays at the top of their arc"] = "otish mashinasini bosing, nishonlarni eng yuqori nuqtada uring",
        ["whack the bugs as they peek out — spare the ladybugs"] = "mo'ralayotgan qo'ng'izlarni uring — xonqizlarga tegmang",
        ["click the strip to drop a disc — the gold slot is the jackpot"] = "disk tashlash uchun chiziqni bosing — oltin katak jekpot",

        // ---- shared game text
        ["Best {0}"] = "Rekord {0}",
        ["NEW BEST!"] = "YANGI REKORD!",
        ["NEW BEST ROUND!"] = "YANGI RAUND REKORDI!",
        ["GAME OVER"] = "O'YIN TUGADI",
        ["ROUND OVER"] = "RAUND TUGADI",
        ["TIME!"] = "VAQT TUGADI!",
        ["{0} points"] = "{0} ochko",
        ["that was a feature!"] = "bu xato emas, imkoniyat edi!",

        // ---- Hoops
        ["Drag the ball, flick it into the hoop"] = "To'pni sudrab, halqaga otib yuboring",
        ["Streak {0} · keep going!"] = "Seriya {0} · davom eting!",
        ["Streak {0} · ON FIRE ×2"] = "Seriya {0} · OLOVDA ×2",
        ["Best streak {0}"] = "Eng uzun seriya {0}",
        ["streak over"] = "seriya tugadi",
        ["DUNK!"] = "DANK!",
        ["SWISH!"] = "TOZA!",
        ["SWISH THREE!"] = "TOZA UCH OCHKOLIK!",
        ["THREE POINTER!"] = "UCH OCHKOLIK!",
        ["NICE SHOT!"] = "ZO'R OTISH!",
        ["ON FIRE!"] = "OLOVDA!",
        ["points ×2"] = "ochkolar ×2",
        ["MOVING HOOP!"] = "HALQA HARAKATDA!",
        ["NEW BEST STREAK"] = "YANGI SERIYA REKORDI",

        // ---- Archery
        ["calm"] = "shamolsiz",
        ["Round {0} · {1} arrows · wind {2}"] = "Raund {0} · o'qlar {1} · shamol {2}",
        ["Round over · pull the bow to play again"] = "Raund tugadi · qayta o'ynash uchun kamonni torting",
        ["Best round {0}"] = "Eng yaxshi raund {0}",
        ["pull back to start a round"] = "raundni boshlash uchun torting",
        ["{0} arrows · wind {1}"] = "o'qlar {0} · shamol {1}",
        ["{0} points · best {1}"] = "{0} ochko · rekord {1}",
        ["BULLSEYE!"] = "MARKAZGA!",
        ["GOLDEN!"] = "OLTIN!",
        ["POP!"] = "PAQ!",

        // ---- Keepy-Uppy
        ["Click the ball to kick it up"] = "To'pni tepish uchun ustiga bosing",
        ["Juggles {0} · grab the star!"] = "Tepishlar {0} · yulduzni oling!",
        ["Juggles {0} · don't let it drop"] = "Tepishlar {0} · tushirmang",
        ["Dropped!"] = "Tushib ketdi!",

        // ---- Mini Golf
        ["Hole {0}/{1} · par {2} · stroke {3}"] = "Chuqurcha {0}/{1} · par {2} · zarba {3}",
        ["Round done · {0} vs par · putt to play again"] = "Raund tugadi · parga nisbatan {0} · qayta o'ynash uchun uring",
        ["Best —"] = "Rekord —",
        ["penalty drop"] = "jarima",
        ["HOLE IN ONE!"] = "BIR ZARBADA!",
        ["EAGLE!"] = "IGL!",
        ["BIRDIE!"] = "BERDI!",
        ["PAR"] = "PAR",
        ["BOGEY"] = "BOGI",
        ["DOUBLE BOGEY"] = "IKKI BOGI",
        ["{0} stroke · par {1}"] = "{0} zarba · par {1}",
        ["{0} strokes · par {1}"] = "{0} zarba · par {1}",
        ["ROUND COMPLETE"] = "RAUND TUGADI",
        ["{0} strokes · {1} vs par"] = "{0} zarba · parga nisbatan {1}",

        // ---- Bug Squash
        ["Squash the sleeping bug to start · spare the ladybugs"] = "Boshlash uchun uxlayotgan qo'ng'izni ezing · xonqizlarga tegmang",
        ["{0}s left · squashed {1}"] = "{0} s qoldi · ezildi {1}",
        ["{0}s left · squashed {1} · combo ×{2}"] = "{0} s qoldi · ezildi {1} · kombo ×{2}",
        ["{0} points · {1} squashed · {2} got away"] = "{0} ochko · {1} ta ezildi · {2} ta qochdi",

        // ---- Can Knockdown
        ["Stack {0} · balls {1} · cans left {2}"] = "Piramida {0} · to'plar {1} · qolgan bankalar {2}",
        ["Game over · grab the ball to play again"] = "O'yin tugadi · qayta o'ynash uchun to'pni oling",
        ["CLEAR!"] = "TOZA!",
        ["+{0} for spare balls"] = "ortiqcha to'plar uchun +{0}",
        ["next stack"] = "keyingi piramida",
        ["{0} points · reached stack {1}"] = "{0} ochko · {1}-piramidagacha yetdingiz",

        // ---- Brick Breaker
        ["Level {0} · balls {1} · bricks {2}"] = "Daraja {0} · to'plar {1} · g'ishtlar {2}",
        ["Level {0} · balls {1} · click the paddle to launch"] = "Daraja {0} · to'plar {1} · boshlash uchun raketkani bosing",
        ["Game over · click the paddle to play again"] = "O'yin tugadi · qayta o'ynash uchun raketkani bosing",
        ["{0} points · level {1}"] = "{0} ochko · daraja {1}",
        ["ball lost"] = "to'p yo'qoldi",
        ["{0} left"] = "{0} ta qoldi",
        ["LEVEL CLEAR!"] = "DARAJA O'TILDI!",
        ["+{0} bonus"] = "+{0} bonus",

        // ---- Bubble Pop
        ["Pop the bubble to start · smaller bubbles score more"] = "Boshlash uchun pufakchani yoring · kichiklari ko'proq ochko beradi",
        ["Wave {0} cleared!"] = "{0}-to'lqin tozalandi!",
        ["Wave {0} · {1}s left · bubbles {2}"] = "To'lqin {0} · {1} s qoldi · pufakchalar {2}",
        ["Wave {0} · {1}s left · bubbles {2} · combo ×{3}"] = "To'lqin {0} · {1} s qoldi · pufakchalar {2} · kombo ×{3}",
        ["pop me"] = "yor meni",
        ["WAVE {0}"] = "{0}-TO'LQIN",
        ["WAVE CLEAR!"] = "TO'LQIN TOZALANDI!",
        ["+{0} time bonus"] = "+{0} vaqt bonusi",
        ["{0} points · wave {1}"] = "{0} ochko · to'lqin {1}",

        // ---- Air Hockey
        ["First to {0} · CPU level {1} · drag your blue mallet"] = "{0} golgacha · kompyuter darajasi {1} · ko'k tayoqchani suring",
        ["Match over · grab your mallet for a rematch"] = "O'yin tugadi · qayta o'ynash uchun tayoqchani oling",
        ["Wins {0}"] = "G'alabalar {0}",
        ["GOAL!"] = "GOL!",
        ["you score"] = "siz gol urdingiz",
        ["CPU scores"] = "kompyuter gol urdi",
        ["Reduce motion"] = "Harakatni kamaytirish",
        ["Colour-blind friendly colours"] = "Rang ko'rlik uchun qulay ranglar",
        ["Accessibility"] = "Qulayliklar",
        ["Cat"] = "Mushuk",
        ["Dog"] = "Kuchuk",
        ["Duck"] = "O'rdak",
        ["Pet"] = "Uy hayvoni",
        ["Make {0} baskets in Hoops"] = "Hoops'da {0} ta to'p tushiring",
        ["Pop {0} balloons in Archery"] = "Kamondan otishda {0} ta shar yorilsin",
        ["Squash {0} bugs"] = "{0} ta qo'ng'izni ezing",
        ["Score {0} goals in Air Hockey"] = "Havo xokkeyida {0} ta gol uring",
        ["Break {0} clays"] = "{0} ta nishonni sindiring",
        ["Break {0} bricks"] = "{0} ta g'ishtni sindiring",
        ["Knock down {0} cans"] = "{0} ta bankani yiqiting",
        ["Pop {0} bubbles"] = "{0} ta pufakni yoring",
        ["Whack {0} bugs"] = "{0} ta qo'ng'izni uring",
        ["Play {0} holes of Mini Golf"] = "Mini golfda {0} ta chuqur o'ynang",
        ["Make {0} perfect drops in Tower Stack"] = "Minorada {0} ta aniq tushirish qiling",
        ["Knock down {0} blocks with the Slingshot"] = "Rogatka bilan {0} ta blokni yiqiting",
        ["Drop {0} Plinko discs"] = "Plinkoda {0} ta disk tashlang",
        ["Swish {0} shots in Hoops"] = "Hoops'da {0} ta toza zarba bering",
        ["Capture {0} pieces in Checkers"] = "Shashkada {0} ta tosh oling",
        ["Capture {0} pieces in Chess"] = "Shaxmatda {0} ta dona oling",
        ["Sink {0} ships in Sea Battle"] = "Dengiz jangida {0} ta kemani cho'ktiring",
        ["Daily challenge done!"] = "Kunlik vazifa bajarildi!",
        ["{0} days in a row"] = "{0} kun ketma-ket",
        ["come back tomorrow for a new one"] = "ertaga yangisi uchun qaytib keling",
        ["Today: {0} ({1}/{2})"] = "Bugun: {0} ({1}/{2})",
        ["{0} · streak {1}"] = "{0} · ketma-ket {1}",
        ["Daily player"] = "Kunlik o'yinchi",
        ["Finish a daily challenge"] = "Kunlik vazifani bajaring",
        ["Seven in a row"] = "Ketma-ket yetti",
        ["Finish the daily challenge 7 days in a row"] = "Kunlik vazifani 7 kun ketma-ket bajaring",
        ["Resumed"] = "Davom etmoqda",
        ["{0} · Claude worked {1}, you played {2}"] = "{0} · Claude {1} ishladi, siz {2} o'ynadingiz",
        ["PAUSED"] = "PAUZA",
        ["click the game to resume"] = "davom ettirish uchun o'yinni bosing",
        ["Pause the game when Claude finishes or needs you"] = "Claude tugatganda yoki sizni kutganda o'yinni to'xtatish",
        ["Shortcuts"] = "Tezkor tugmalar",
        ["Modifier keys"] = "Yordamchi tugmalar",
        ["Show or hide the overlay"] = "O'yinni ko'rsatish yoki yashirish",
        ["Save"] = "Saqlash",
        ["Defaults"] = "Standart",
        ["Use three different letters, A to Z."] = "A dan Z gacha uchta har xil harf tanlang.",
        ["Saved: {0}. They take effect the next time Desk Arcade starts."] = "Saqlandi: {0}. Desk Arcade keyingi safar ishga tushganda kuchga kiradi.",
        ["Saved: {0}"] = "Saqlandi: {0}",
        ["Saved, but another app already uses one of these ({0}). Try other letters or keys."] = "Saqlandi, lekin ulardan birini boshqa dastur ishlatmoqda ({0}). Boshqa harf yoki tugmalarni tanlang.",
        ["Shortcuts…"] = "Tezkor tugmalar…",
        ["Race {0}: start a round and they start too"] = "{0} bilan poyga: raund boshlang, u ham boshlaydi",
        ["{0}: {1}{2}"] = "{0}: {1}{2}",
        ["done"] = "tugadi",
        ["DEAD HEAT"] = "DURANG",
        ["YOU WIN THE RACE!"] = "POYGADA YUTDINGIZ!",
        ["{0} WINS THE RACE"] = "POYGADA {0} YUTDI",
        ["{0} – {1}"] = "{0} – {1}",
        ["H-O-R-S-E over · grab the ball for a rematch"] = "H-O-R-S-E tugadi · qayta o'ynash uchun to'pni oling",
        ["Match the shot from the marked spot, or take a letter"] = "Belgilangan joydan xuddi shunday oting, aks holda harf olasiz",
        ["{0} has to match your shot"] = "{0} sizning zarbangizni takrorlashi kerak",
        ["H-O-R-S-E · set a shot from anywhere"] = "H-O-R-S-E · istalgan joydan zarba bering",
        ["H-O-R-S-E · {0} is setting a shot"] = "H-O-R-S-E · {0} zarba bermoqda",
        ["shoot from here"] = "shu yerdan oting",
        ["{0}'s shot"] = "{0} ning navbati",
        ["shoot from the marked spot"] = "belgilangan joydan oting",
        ["{0} made it — your turn to match"] = "{0} tushirdi — endi siz takrorlang",
        ["you take a letter"] = "siz harf oldingiz",
        ["{0} takes a letter"] = "{0} harf oldi",
        ["grab the ball for a rematch"] = "qayta o'ynash uchun to'pni oling",
        ["Find games"] = "O'yinlarni topish",
        ["Looking for games on your network…"] = "Tarmoqda o'yinlar qidirilmoqda…",
        ["Join"] = "Qo'shilish",
        ["Or join by address (ask the host for their IP):"] = "Yoki manzil orqali qo'shiling (o'yin ochgandan IP manzilini so'rang):",
        ["{0} · {1} · already playing"] = "{0} · {1} · allaqachon o'ynayapti",
        ["{0} · {1}"] = "{0} · {1}",
        ["No games yet. Ask your co-worker to pick Play over LAN → Host a game."] = "Hozircha o'yin yo'q. Hamkasbingizdan Tarmoq orqali o'ynash → O'yin ochishni tanlashini so'rang.",
        ["Click a game to join it:"] = "Qo'shilish uchun o'yinni bosing:",
        ["Couldn't search the network."] = "Tarmoqni qidirib bo'lmadi.",
        ["That doesn't look like an address, e.g. 192.168.1.20"] = "Bu manzilga o'xshamaydi, masalan 192.168.1.20",
        ["sent to {0}"] = "{0} ga yuborildi",
        ["from {0}"] = "{0} dan",
        ["Find games / join by address…"] = "O'yin topish / manzil orqali qo'shilish…",
        ["Send"] = "Yuborish",
        ["gg"] = "gg",
        ["One more?"] = "Yana bittami?",
        ["Nice shot!"] = "Zo'r zarba!",
        ["Your move!"] = "Sizning navbatingiz!",
        ["Ha!"] = "Ha-ha!",
        ["Crowned"] = "Toj kiydi",
        ["Win a game of Checkers"] = "Shashkada bir marta yuting",
        ["Checkmate"] = "Mat",
        ["Win a game of Chess"] = "Shaxmatda bir marta yuting",
        ["Four in a row"] = "To'rttasi qatorda",
        ["Win a game of Connect Four"] = "To'rtta qatorda bir marta yuting",
        ["Three in a row"] = "Uchtasi qatorda",
        ["Win a game of Tic-tac-toe"] = "X-O da bir marta yuting",
        ["Admiral"] = "Admiral",
        ["Win a game of Sea Battle"] = "Dengiz jangida bir marta yuting",
        ["Office rival"] = "Ofisdagi raqib",
        ["Beat a co-worker over the LAN"] = "Tarmoq orqali hamkasbingizni yuting",
        ["Sea Battle"] = "Dengiz jangi",
        ["click the enemy grid to start, then fire — a hit shoots again"] = "boshlash uchun dushman maydonini bosing, keyin o'q uzing — tekkizsangiz yana otasiz",
        ["Waiting for {0} to get ready…"] = "{0} tayyor bo'lishi kutilmoqda…",
        ["Click your grid to move your ships · click the enemy grid to start"] = "Kemalarni joylashtirish uchun o'z maydoningizni bosing · boshlash uchun dushman maydonini bosing",
        ["Game over · click a grid for a rematch"] = "O'yin tugadi · qayta o'ynash uchun maydonni bosing",
        ["Your shot · click the enemy grid · a hit shoots again"] = "Sizning navbatingiz · dushman maydonini bosing · tekkizsangiz yana otasiz",
        ["{0} is aiming…"] = "{0} nishonga olmoqda…",
        ["SUNK!"] = "CHO'KDI!",
        ["Ship lost"] = "Kema yo'qotildi",
        ["click a grid for a rematch"] = "qayta o'ynash uchun maydonni bosing",
        ["Your fleet"] = "Sizning flotingiz",
        ["Enemy waters"] = "Dushman suvlari",
        ["Your move · click a square · right-drag moves the board"] = "Sizning yurishingiz · katakni bosing · taxtani o'ng tugma bilan suring",
        ["Tic-tac-toe"] = "X-O",
        ["Connect Four"] = "To'rtta qator",
        ["The board is full"] = "Taxta to'ldi",
        ["click a column to drop a disc — four in a row wins"] = "diskni tashlash uchun ustunni bosing — to'rttasi qatorda yutadi",
        ["click a square — three in a row wins"] = "katakni bosing — uchtasi qatorda yutadi",
        ["Chess"] = "Shaxmat",
        ["Stalemate"] = "Pat",
        ["50 moves without a capture or pawn move"] = "50 yurish davomida hech narsa olinmadi va piyoda yurmadi",
        ["Not enough pieces to mate"] = "Mat qilish uchun donalar yetarli emas",
        ["40 moves without a capture"] = "40 yurish davomida hech narsa olinmadi",
        ["DRAW"] = "DURANG",
        ["40 moves without a capture · click the board for a rematch"] = "40 yurish davomida hech narsa olinmadi · qayta o'ynash uchun taxtani bosing",
        ["Checkers"] = "Shashka",
        ["click a piece, then the square it should move to"] = "toshni bosing, keyin u boradigan katakni",
        ["Game over · click the board for a rematch"] = "O'yin tugadi · qayta o'ynash uchun taxtani bosing",
        ["Your move · click a piece, then where it goes · right-drag moves the board"] = "Sizning yurishingiz · toshni, keyin katakni bosing · taxtani o'ng tugma bilan suring",
        ["{0} is thinking…"] = "{0} o'ylayapti…",
        ["DOUBLE JUMP!"] = "IKKITA OLDI!",
        ["TRIPLE JUMP!"] = "UCHTA OLDI!",
        ["vs {0}"] = "{0} bilan",
        ["click the board for a rematch"] = "qayta o'ynash uchun taxtani bosing",
        ["Play over LAN"] = "Tarmoq orqali o'ynash",
        ["Host a game"] = "O'yin ochish",
        ["Join a game"] = "O'yinga qo'shilish",
        ["Leave"] = "Chiqish",
        ["Not connected"] = "Ulanmagan",
        ["Can't host"] = "O'yin ochib bo'lmadi",
        ["UDP port {0} is in use"] = "UDP {0} porti band",
        ["Waiting for a player to join…"] = "O'yinchi qo'shilishi kutilmoqda…",
        ["Looking for a host…"] = "O'yin qidirilmoqda…",
        ["Playing with {0}"] = "{0} bilan o'ynayapsiz",
        ["Connected"] = "Ulandi",
        ["Hosting"] = "O'yin ochildi",
        ["CPU"] = "Kompyuter",
        ["First to {0} · vs {1} over LAN · drag your blue mallet"] = "{0} golgacha · tarmoqda {1} bilan · ko'k tayoqchani torting",
        ["{0} scores"] = "{0} gol urdi",
        ["{0}–{1} vs {2}"] = "{0}–{1} · {2} bilan",
        ["{0} WINS"] = "{0} YUTDI",
        ["YOU  {0} : {1}  {2}"] = "SIZ  {0} : {1}  {2}",
        ["YOU WIN!"] = "SIZ YUTDINGIZ!",
        ["CPU WINS"] = "KOMPYUTER YUTDI",
        ["{0}–{1} · the CPU gets faster"] = "{0}–{1} · kompyuter tezlashadi",
        ["{0}–{1} · grab your mallet for a rematch"] = "{0}–{1} · qayta o'ynash uchun tayoqchani oling",
        ["YOU  {0} : {1}  CPU"] = "SIZ  {0} : {1}  KOMP",

        // ---- Whack-a-Bug
        ["{0}s left · whacked {1}"] = "{0} s qoldi · urildi {1}",
        ["Whack the sleepy bug to start · spare the ladybugs"] = "Boshlash uchun mudrayotgan qo'ng'izni uring · xonqizlarga tegmang",
        ["{0} points · {1} whacked"] = "{0} ochko · {1} ta urildi",

        // ---- Clay Shooting
        ["Click the trap machine to start · shoot the clays"] = "Boshlash uchun otish mashinasini bosing · nishonlarni uring",
        ["click to start"] = "boshlash uchun bosing",
        ["DOUBLE!"] = "DUPLET!",
        ["Last round {0}/{1} · click the trap to go again"] = "Oxirgi raund {0}/{1} · qayta boshlash uchun mashinani bosing",
        ["Pull {0}/{1} · hits {2}"] = "Otish {0}/{1} · tegdi {2}",
        ["still rising"] = "hali ko'tarilmoqda",
        ["{0} of {1} clays hit · {2} points"] = "{1} tadan {0} ta nishon · {2} ochko",

        // ---- Plinko
        ["click to drop · right-drag to move"] = "tashlash uchun bosing · surish uchun o'ng tugma bilan torting",
        ["click for a new round"] = "yangi raund uchun bosing",
        ["Round over · click the drop strip to play again"] = "Raund tugadi · qayta o'ynash uchun tashlash chizig'ini bosing",
        ["Discs {0} · jackpots {1}"] = "Disklar {0} · jekpotlar {1}",
        ["{0} points · {1} jackpots"] = "{0} ochko · {1} jekpot",
        ["JACKPOT!"] = "JEKPOT!",

        // ---- Tower Stack
        ["Tower Stack"] = "Minora",
        ["click the sliding block to drop it — stack as high as you can"] = "sirpanayotgan blokni tashlash uchun bosing — iloji boricha baland quring",
        ["Height {0} · click the block to drop it"] = "Balandlik {0} · tashlash uchun blokni bosing",
        ["Game over · click the block to play again"] = "O'yin tugadi · qayta o'ynash uchun blokni bosing",
        ["PERFECT!"] = "MUKAMMAL!",
        ["wider block"] = "kengroq blok",
        ["Height {0}"] = "Balandlik {0}",

        // ---- Slingshot
        ["Slingshot"] = "Sopqon",
        ["drag back from the slingshot and let go — knock the tower down"] = "sopqondan orqaga torting va qo'yib yuboring — minorani yiqiting",
        ["Tower {0} · stones {1} · blocks {2}"] = "Minora {0} · toshlar {1} · bloklar {2}",
        ["Game over · pull the stone to play again"] = "O'yin tugadi · qayta o'ynash uchun toshni torting",
        ["+{0} · spare stones {1}"] = "+{0} · ortiqcha toshlar {1}",
        ["next tower"] = "keyingi minora",
        ["Tower collapsed"] = "Minora quladi",
        ["building a new one"] = "yangisi qurilmoqda",
        ["{0} points · tower {1}"] = "{0} ochko · minora {1}",

        // ---- Desktop Pet
        ["Desktop Pet"] = "Uy hayvoni",
        ["click the pet to pet it — drag to carry and throw it"] = "erkalash uchun hayvonchani bosing — ko'tarib otish uchun torting",
        ["Sleeping · click to wake"] = "Uxlayapti · uyg'otish uchun bosing",
        ["Wheee! · let go to throw"] = "Uuuh! · otish uchun qo'yib yuboring",
        ["Wheee!"] = "Uuuh!",
        ["Wants attention · click to pet"] = "E'tibor so'rayapti · erkalash uchun bosing",
        ["Exploring the window tops"] = "Oynalar tepasini kezmoqda",
        ["Click to pet · drag to carry"] = "Erkalash uchun bosing · ko'tarish uchun torting",
        ["Pets {0}"] = "Erkalashlar {0}",
        ["z z"] = "z z",

        // ---- achievements
        ["Coffee break"] = "Qahva tanaffusi",
        ["Play for 30 minutes in total"] = "Jami 30 daqiqa o'ynang",
        ["Marathon"] = "Marafon",
        ["Play for 5 hours in total"] = "Jami 5 soat o'ynang",
        ["Explorer"] = "Kashfiyotchi",
        ["Play 6 different games"] = "6 xil o'yin o'ynang",
        ["Pair programmer"] = "Juftlikda dasturchi",
        ["Be playing when Claude finishes 10 times"] = "Claude ishni tugatganda 10 marta o'yinda bo'ling",
        ["Hundred baskets"] = "Yuzta to'p",
        ["Score 100 baskets"] = "100 ta to'p kiriting",
        ["Nothing but net"] = "Faqat to'r",
        ["Score 25 swishes"] = "25 marta toza kiriting",
        ["Unstoppable"] = "To'xtatib bo'lmas",
        ["Make 10 baskets in a row"] = "Ketma-ket 10 ta to'p kiriting",
        ["Bullseye"] = "Nishon markazi",
        ["Hit 10 bullseyes"] = "Markazga 10 marta tegizing",
        ["Party pooper"] = "Bayram buzar",
        ["Pop 50 balloons"] = "50 ta sharni yoring",
        ["Sharpshooter"] = "Mergan",
        ["Score 80 points in one round"] = "Bir raundda 80 ochko to'plang",
        ["Keepy-uppy pro"] = "To'p tepish ustasi",
        ["Score 25 points in one run"] = "Bir urinishda 25 ochko to'plang",
        ["Star catcher"] = "Yulduz tutuvchi",
        ["Catch 20 stars"] = "20 ta yulduz tuting",
        ["Hole in one"] = "Bir zarbada",
        ["Sink a hole in one"] = "Bir zarbada chuqurchaga kiriting",
        ["Course regular"] = "Maydon faxriysi",
        ["Finish 50 holes"] = "50 ta chuqurchani tugating",
        ["Under par"] = "Pardan kam",
        ["Finish a round under par"] = "Raundni pardan kam zarbada tugating",
        ["Exterminator"] = "Yo'q qiluvchi",
        ["Squash 200 bugs"] = "200 ta qo'ng'izni ezing",
        ["Combo breaker"] = "Kombo ustasi",
        ["Reach a ×4 combo"] = "×4 komboga yeting",
        ["Zero bugs"] = "Xatosiz",
        ["Score 60 points in one round"] = "Bir raundda 60 ochko to'plang",
        ["Tin smasher"] = "Banka ezuvchi",
        ["Knock down 100 cans"] = "100 ta bankani yiqiting",
        ["Fairground champion"] = "Yarmarka chempioni",
        ["Reach stack 5"] = "5-piramidaga yeting",
        ["Demolition crew"] = "Buzuvchilar brigadasi",
        ["Break 500 bricks"] = "500 ta g'ishtni sindiring",
        ["Wall breaker"] = "Devor buzar",
        ["Reach level 4"] = "4-darajaga yeting",
        ["Bubble wrap"] = "Pufakchali plyonka",
        ["Pop 300 bubbles"] = "300 ta pufakcha yoring",
        ["Wave rider"] = "To'lqin ustasi",
        ["Reach wave 5"] = "5-to'lqinga yeting",
        ["First win"] = "Birinchi g'alaba",
        ["Beat the CPU"] = "Kompyuterni yenging",
        ["Sniper"] = "Snayper",
        ["Score 50 goals"] = "50 ta gol uring",
        ["Champion"] = "Chempion",
        ["Beat CPU level 5"] = "Kompyuterni 5-darajada yenging",
        ["Best friends"] = "Eng yaqin do'stlar",
        ["Pet your desktop pet 50 times"] = "Uy hayvoningizni 50 marta erkalang",
        ["Taxi"] = "Taksi",
        ["Carry your pet 10 times"] = "Uy hayvoningizni 10 marta ko'tarib boring",
        ["Skyscraper"] = "Osmono'par bino",
        ["Build a tower 15 blocks high"] = "15 blok balandlikda minora quring",
        ["Perfectionist"] = "Mukammallikparast",
        ["Make 10 perfect drops"] = "10 marta mukammal tashlang",
        ["Wrecking ball"] = "Buzuvchi shar",
        ["Knock down 200 blocks"] = "200 ta blokni yiqiting",
        ["Clean sweep"] = "Toza g'alaba",
        ["Clear 10 towers"] = "10 ta minorani tozalang",
        ["Bug whacker"] = "Qo'ng'iz uruvchi",
        ["Whack 200 bugs"] = "200 ta qo'ng'izni uring",
        ["Lightning hands"] = "Chaqqon qo'llar",
        ["Score 50 points in one round"] = "Bir raundda 50 ochko to'plang",
        ["Clay breaker"] = "Nishon sindiruvchi",
        ["Hit 100 clay targets"] = "100 ta loy nishonni uring",
        ["Double trouble"] = "Ikki karra omad",
        ["Hit two targets with one shot"] = "Bitta o'q bilan ikki nishonni uring",
        ["Jackpot"] = "Jekpot",
        ["Land 5 discs in the jackpot slot"] = "Jekpot katagiga 5 ta disk tushiring",
        ["Disc dropper"] = "Disk tashlovchi",
        ["Drop 100 discs"] = "100 ta disk tashlang",
    };
}
